/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input [3:0] hdmi2_tmds,
    input [3:0] hdmi2_tmdsb,
    inout hdmi2_sda,
    input hdmi2_scl,
    output reg apa102_data0,
    output reg apa102_data1,
    output reg apa102_data2,
    output reg apa102_data3,
    output reg apa102_data4,
    output reg apa102_data5,
    output reg apa102_data6,
    output reg apa102_data7,
    output reg apa102_data8,
    output reg apa102_data9,
    output reg apa102_data10,
    output reg apa102_data11,
    output reg apa102_data12,
    output reg apa102_data13,
    output reg apa102_data14,
    output reg apa102_data15,
    output reg apa102_data16,
    output reg apa102_data17,
    output reg apa102_data18,
    output reg apa102_data19,
    output reg apa102_data20,
    output reg apa102_data21,
    output reg apa102_data22,
    output reg apa102_data23,
    output reg apa102_data24,
    output reg apa102_data25,
    output reg apa102_data26,
    output reg apa102_data27,
    output reg apa102_data28,
    output reg apa102_data29,
    output reg apa102_data30,
    output reg apa102_data31,
    output reg apa102_data32,
    output reg apa102_sck
  );
  
  
  
  reg rst;
  
  wire [10-1:0] M_panelRows_startPixel0;
  wire [10-1:0] M_panelRows_startPixel1;
  wire [10-1:0] M_panelRows_startPixel2;
  wire [10-1:0] M_panelRows_rowPixelPanel0;
  wire [10-1:0] M_panelRows_rowPixelPanel1;
  wire [10-1:0] M_panelRows_rowPixelPanel2;
  wire [10-1:0] M_panelRows_rowPixelPanel3;
  wire [10-1:0] M_panelRows_rowPixelPanel4;
  wire [10-1:0] M_panelRows_rowPixelPanel5;
  wire [10-1:0] M_panelRows_rowPixelPanel7;
  reg [4-1:0] M_panelRows_currentFrame;
  reg [5-1:0] M_panelRows_address0;
  panelRows_1 panelRows (
    .currentFrame(M_panelRows_currentFrame),
    .address0(M_panelRows_address0),
    .startPixel0(M_panelRows_startPixel0),
    .startPixel1(M_panelRows_startPixel1),
    .startPixel2(M_panelRows_startPixel2),
    .rowPixelPanel0(M_panelRows_rowPixelPanel0),
    .rowPixelPanel1(M_panelRows_rowPixelPanel1),
    .rowPixelPanel2(M_panelRows_rowPixelPanel2),
    .rowPixelPanel3(M_panelRows_rowPixelPanel3),
    .rowPixelPanel4(M_panelRows_rowPixelPanel4),
    .rowPixelPanel5(M_panelRows_rowPixelPanel5),
    .rowPixelPanel7(M_panelRows_rowPixelPanel7)
  );
  
  wire [1-1:0] M_hdmi_to_fifo_printSomething;
  wire [8-1:0] M_hdmi_to_fifo_redOut;
  wire [8-1:0] M_hdmi_to_fifo_greenOut;
  wire [8-1:0] M_hdmi_to_fifo_blueOut;
  wire [1-1:0] M_hdmi_to_fifo_writeFifo;
  wire [1-1:0] M_hdmi_to_fifo_hdmiClk;
  wire [1-1:0] M_hdmi_to_fifo_hdmi_vsyncFlag;
  wire [24-1:0] M_hdmi_to_fifo_pixelNumber;
  wire [2-1:0] M_hdmi_to_fifo_globalReadWriteStageFlag;
  wire [1-1:0] M_hdmi_to_fifo_out;
  reg [4-1:0] M_hdmi_to_fifo_tmds;
  reg [4-1:0] M_hdmi_to_fifo_tmdsb;
  hdmi_to_fifo_2 hdmi_to_fifo (
    .rst(rst),
    .tmds(M_hdmi_to_fifo_tmds),
    .tmdsb(M_hdmi_to_fifo_tmdsb),
    .printSomething(M_hdmi_to_fifo_printSomething),
    .redOut(M_hdmi_to_fifo_redOut),
    .greenOut(M_hdmi_to_fifo_greenOut),
    .blueOut(M_hdmi_to_fifo_blueOut),
    .writeFifo(M_hdmi_to_fifo_writeFifo),
    .hdmiClk(M_hdmi_to_fifo_hdmiClk),
    .hdmi_vsyncFlag(M_hdmi_to_fifo_hdmi_vsyncFlag),
    .pixelNumber(M_hdmi_to_fifo_pixelNumber),
    .globalReadWriteStageFlag(M_hdmi_to_fifo_globalReadWriteStageFlag),
    .out(M_hdmi_to_fifo_out)
  );
  
  reg fclk;
  
  wire [1-1:0] M_clk_wiz_CLK_OUT1;
  reg [1-1:0] M_clk_wiz_CLK_IN1;
  clk_wiz_v3_6 clk_wiz (
    .CLK_IN1(M_clk_wiz_CLK_IN1),
    .CLK_OUT1(M_clk_wiz_CLK_OUT1)
  );
  
  always @* begin
    M_clk_wiz_CLK_IN1 = clk;
    fclk = M_clk_wiz_CLK_OUT1;
  end
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_3 reset_cond (
    .clk(fclk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_panel_0_newSpiData;
  wire [8-1:0] M_panel_0_ledByteOut;
  wire [10-1:0] M_panel_0_ramPixelAddress;
  wire [1-1:0] M_panel_0_idle;
  wire [1-1:0] M_panel_0_printSomething;
  wire [1-1:0] M_panel_0_out;
  reg [1-1:0] M_panel_0_spiBusySignal;
  reg [24-1:0] M_panel_0_rgbIn;
  reg [1-1:0] M_panel_0_startWritingFlag;
  panel_0_4 panel_0 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_0_spiBusySignal),
    .rgbIn(M_panel_0_rgbIn),
    .startWritingFlag(M_panel_0_startWritingFlag),
    .newSpiData(M_panel_0_newSpiData),
    .ledByteOut(M_panel_0_ledByteOut),
    .ramPixelAddress(M_panel_0_ramPixelAddress),
    .idle(M_panel_0_idle),
    .printSomething(M_panel_0_printSomething),
    .out(M_panel_0_out)
  );
  wire [1-1:0] M_panel_1_newSpiData;
  wire [8-1:0] M_panel_1_ledByteOut;
  wire [10-1:0] M_panel_1_ramPixelAddress;
  wire [1-1:0] M_panel_1_idle;
  wire [1-1:0] M_panel_1_printSomething;
  wire [1-1:0] M_panel_1_out;
  reg [1-1:0] M_panel_1_spiBusySignal;
  reg [24-1:0] M_panel_1_rgbIn;
  reg [1-1:0] M_panel_1_startWritingFlag;
  panel_1_5 panel_1 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_1_spiBusySignal),
    .rgbIn(M_panel_1_rgbIn),
    .startWritingFlag(M_panel_1_startWritingFlag),
    .newSpiData(M_panel_1_newSpiData),
    .ledByteOut(M_panel_1_ledByteOut),
    .ramPixelAddress(M_panel_1_ramPixelAddress),
    .idle(M_panel_1_idle),
    .printSomething(M_panel_1_printSomething),
    .out(M_panel_1_out)
  );
  wire [1-1:0] M_panel_2_newSpiData;
  wire [8-1:0] M_panel_2_ledByteOut;
  wire [10-1:0] M_panel_2_ramPixelAddress;
  wire [1-1:0] M_panel_2_idle;
  wire [8-1:0] M_panel_2_transmitByte;
  wire [1-1:0] M_panel_2_newTxDataFlag;
  wire [1-1:0] M_panel_2_out;
  reg [1-1:0] M_panel_2_spiBusySignal;
  reg [24-1:0] M_panel_2_rgbIn;
  reg [1-1:0] M_panel_2_startWritingFlag;
  panel_2_6 panel_2 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_2_spiBusySignal),
    .rgbIn(M_panel_2_rgbIn),
    .startWritingFlag(M_panel_2_startWritingFlag),
    .newSpiData(M_panel_2_newSpiData),
    .ledByteOut(M_panel_2_ledByteOut),
    .ramPixelAddress(M_panel_2_ramPixelAddress),
    .idle(M_panel_2_idle),
    .transmitByte(M_panel_2_transmitByte),
    .newTxDataFlag(M_panel_2_newTxDataFlag),
    .out(M_panel_2_out)
  );
  wire [1-1:0] M_panel_3_newSpiData;
  wire [8-1:0] M_panel_3_ledByteOut;
  wire [10-1:0] M_panel_3_ramPixelAddress;
  wire [1-1:0] M_panel_3_idle;
  wire [1-1:0] M_panel_3_out;
  reg [1-1:0] M_panel_3_spiBusySignal;
  reg [24-1:0] M_panel_3_rgbIn;
  reg [1-1:0] M_panel_3_startWritingFlag;
  panel_3_7 panel_3 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_3_spiBusySignal),
    .rgbIn(M_panel_3_rgbIn),
    .startWritingFlag(M_panel_3_startWritingFlag),
    .newSpiData(M_panel_3_newSpiData),
    .ledByteOut(M_panel_3_ledByteOut),
    .ramPixelAddress(M_panel_3_ramPixelAddress),
    .idle(M_panel_3_idle),
    .out(M_panel_3_out)
  );
  wire [1-1:0] M_panel_4_newSpiData;
  wire [8-1:0] M_panel_4_ledByteOut;
  wire [10-1:0] M_panel_4_ramPixelAddress;
  wire [1-1:0] M_panel_4_idle;
  wire [1-1:0] M_panel_4_out;
  reg [1-1:0] M_panel_4_spiBusySignal;
  reg [24-1:0] M_panel_4_rgbIn;
  reg [1-1:0] M_panel_4_startWritingFlag;
  panel_4_8 panel_4 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_4_spiBusySignal),
    .rgbIn(M_panel_4_rgbIn),
    .startWritingFlag(M_panel_4_startWritingFlag),
    .newSpiData(M_panel_4_newSpiData),
    .ledByteOut(M_panel_4_ledByteOut),
    .ramPixelAddress(M_panel_4_ramPixelAddress),
    .idle(M_panel_4_idle),
    .out(M_panel_4_out)
  );
  wire [1-1:0] M_panel_5_newSpiData;
  wire [8-1:0] M_panel_5_ledByteOut;
  wire [10-1:0] M_panel_5_ramPixelAddress;
  wire [1-1:0] M_panel_5_idle;
  wire [1-1:0] M_panel_5_printSomething;
  wire [1-1:0] M_panel_5_out;
  reg [1-1:0] M_panel_5_spiBusySignal;
  reg [24-1:0] M_panel_5_rgbIn;
  reg [1-1:0] M_panel_5_startWritingFlag;
  panel_5_9 panel_5 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_5_spiBusySignal),
    .rgbIn(M_panel_5_rgbIn),
    .startWritingFlag(M_panel_5_startWritingFlag),
    .newSpiData(M_panel_5_newSpiData),
    .ledByteOut(M_panel_5_ledByteOut),
    .ramPixelAddress(M_panel_5_ramPixelAddress),
    .idle(M_panel_5_idle),
    .printSomething(M_panel_5_printSomething),
    .out(M_panel_5_out)
  );
  wire [1-1:0] M_panel_6_newSpiData;
  wire [8-1:0] M_panel_6_ledByteOut;
  wire [10-1:0] M_panel_6_ramPixelAddress;
  wire [1-1:0] M_panel_6_idle;
  wire [1-1:0] M_panel_6_out;
  reg [1-1:0] M_panel_6_spiBusySignal;
  reg [24-1:0] M_panel_6_rgbIn;
  reg [1-1:0] M_panel_6_startWritingFlag;
  panel_6_10 panel_6 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_6_spiBusySignal),
    .rgbIn(M_panel_6_rgbIn),
    .startWritingFlag(M_panel_6_startWritingFlag),
    .newSpiData(M_panel_6_newSpiData),
    .ledByteOut(M_panel_6_ledByteOut),
    .ramPixelAddress(M_panel_6_ramPixelAddress),
    .idle(M_panel_6_idle),
    .out(M_panel_6_out)
  );
  wire [1-1:0] M_panel_7_newSpiData;
  wire [8-1:0] M_panel_7_ledByteOut;
  wire [10-1:0] M_panel_7_ramPixelAddress;
  wire [1-1:0] M_panel_7_idle;
  wire [1-1:0] M_panel_7_out;
  reg [1-1:0] M_panel_7_spiBusySignal;
  reg [24-1:0] M_panel_7_rgbIn;
  reg [1-1:0] M_panel_7_startWritingFlag;
  panel_7_11 panel_7 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_7_spiBusySignal),
    .rgbIn(M_panel_7_rgbIn),
    .startWritingFlag(M_panel_7_startWritingFlag),
    .newSpiData(M_panel_7_newSpiData),
    .ledByteOut(M_panel_7_ledByteOut),
    .ramPixelAddress(M_panel_7_ramPixelAddress),
    .idle(M_panel_7_idle),
    .out(M_panel_7_out)
  );
  wire [1-1:0] M_panel_8_newSpiData;
  wire [8-1:0] M_panel_8_ledByteOut;
  wire [10-1:0] M_panel_8_ramPixelAddress;
  wire [1-1:0] M_panel_8_idle;
  wire [1-1:0] M_panel_8_out;
  reg [1-1:0] M_panel_8_spiBusySignal;
  reg [24-1:0] M_panel_8_rgbIn;
  reg [1-1:0] M_panel_8_startWritingFlag;
  panel_8_12 panel_8 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_8_spiBusySignal),
    .rgbIn(M_panel_8_rgbIn),
    .startWritingFlag(M_panel_8_startWritingFlag),
    .newSpiData(M_panel_8_newSpiData),
    .ledByteOut(M_panel_8_ledByteOut),
    .ramPixelAddress(M_panel_8_ramPixelAddress),
    .idle(M_panel_8_idle),
    .out(M_panel_8_out)
  );
  wire [1-1:0] M_panel_9_newSpiData;
  wire [8-1:0] M_panel_9_ledByteOut;
  wire [10-1:0] M_panel_9_ramPixelAddress;
  wire [1-1:0] M_panel_9_idle;
  wire [1-1:0] M_panel_9_out;
  reg [1-1:0] M_panel_9_spiBusySignal;
  reg [24-1:0] M_panel_9_rgbIn;
  reg [1-1:0] M_panel_9_startWritingFlag;
  panel_9_13 panel_9 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_9_spiBusySignal),
    .rgbIn(M_panel_9_rgbIn),
    .startWritingFlag(M_panel_9_startWritingFlag),
    .newSpiData(M_panel_9_newSpiData),
    .ledByteOut(M_panel_9_ledByteOut),
    .ramPixelAddress(M_panel_9_ramPixelAddress),
    .idle(M_panel_9_idle),
    .out(M_panel_9_out)
  );
  wire [1-1:0] M_panel_10_newSpiData;
  wire [8-1:0] M_panel_10_ledByteOut;
  wire [10-1:0] M_panel_10_ramPixelAddress;
  wire [1-1:0] M_panel_10_idle;
  wire [1-1:0] M_panel_10_printSomething;
  wire [1-1:0] M_panel_10_out;
  reg [1-1:0] M_panel_10_spiBusySignal;
  reg [24-1:0] M_panel_10_rgbIn;
  reg [1-1:0] M_panel_10_startWritingFlag;
  panel_10_14 panel_10 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_10_spiBusySignal),
    .rgbIn(M_panel_10_rgbIn),
    .startWritingFlag(M_panel_10_startWritingFlag),
    .newSpiData(M_panel_10_newSpiData),
    .ledByteOut(M_panel_10_ledByteOut),
    .ramPixelAddress(M_panel_10_ramPixelAddress),
    .idle(M_panel_10_idle),
    .printSomething(M_panel_10_printSomething),
    .out(M_panel_10_out)
  );
  wire [1-1:0] M_panel_11_newSpiData;
  wire [8-1:0] M_panel_11_ledByteOut;
  wire [10-1:0] M_panel_11_ramPixelAddress;
  wire [1-1:0] M_panel_11_idle;
  wire [8-1:0] M_panel_11_transmitByte;
  wire [1-1:0] M_panel_11_newTxDataFlag;
  wire [1-1:0] M_panel_11_out;
  reg [1-1:0] M_panel_11_spiBusySignal;
  reg [24-1:0] M_panel_11_rgbIn;
  reg [1-1:0] M_panel_11_startWritingFlag;
  panel_11_15 panel_11 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_11_spiBusySignal),
    .rgbIn(M_panel_11_rgbIn),
    .startWritingFlag(M_panel_11_startWritingFlag),
    .newSpiData(M_panel_11_newSpiData),
    .ledByteOut(M_panel_11_ledByteOut),
    .ramPixelAddress(M_panel_11_ramPixelAddress),
    .idle(M_panel_11_idle),
    .transmitByte(M_panel_11_transmitByte),
    .newTxDataFlag(M_panel_11_newTxDataFlag),
    .out(M_panel_11_out)
  );
  wire [1-1:0] M_panel_12_newSpiData;
  wire [8-1:0] M_panel_12_ledByteOut;
  wire [10-1:0] M_panel_12_ramPixelAddress;
  wire [1-1:0] M_panel_12_idle;
  wire [1-1:0] M_panel_12_out;
  reg [1-1:0] M_panel_12_spiBusySignal;
  reg [24-1:0] M_panel_12_rgbIn;
  reg [1-1:0] M_panel_12_startWritingFlag;
  panel_12_16 panel_12 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_12_spiBusySignal),
    .rgbIn(M_panel_12_rgbIn),
    .startWritingFlag(M_panel_12_startWritingFlag),
    .newSpiData(M_panel_12_newSpiData),
    .ledByteOut(M_panel_12_ledByteOut),
    .ramPixelAddress(M_panel_12_ramPixelAddress),
    .idle(M_panel_12_idle),
    .out(M_panel_12_out)
  );
  wire [1-1:0] M_panel_13_newSpiData;
  wire [8-1:0] M_panel_13_ledByteOut;
  wire [10-1:0] M_panel_13_ramPixelAddress;
  wire [1-1:0] M_panel_13_idle;
  wire [1-1:0] M_panel_13_out;
  reg [1-1:0] M_panel_13_spiBusySignal;
  reg [24-1:0] M_panel_13_rgbIn;
  reg [1-1:0] M_panel_13_startWritingFlag;
  panel_13_17 panel_13 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_13_spiBusySignal),
    .rgbIn(M_panel_13_rgbIn),
    .startWritingFlag(M_panel_13_startWritingFlag),
    .newSpiData(M_panel_13_newSpiData),
    .ledByteOut(M_panel_13_ledByteOut),
    .ramPixelAddress(M_panel_13_ramPixelAddress),
    .idle(M_panel_13_idle),
    .out(M_panel_13_out)
  );
  wire [1-1:0] M_panel_14_newSpiData;
  wire [8-1:0] M_panel_14_ledByteOut;
  wire [10-1:0] M_panel_14_ramPixelAddress;
  wire [1-1:0] M_panel_14_idle;
  wire [1-1:0] M_panel_14_out;
  reg [1-1:0] M_panel_14_spiBusySignal;
  reg [24-1:0] M_panel_14_rgbIn;
  reg [1-1:0] M_panel_14_startWritingFlag;
  panel_14_18 panel_14 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_14_spiBusySignal),
    .rgbIn(M_panel_14_rgbIn),
    .startWritingFlag(M_panel_14_startWritingFlag),
    .newSpiData(M_panel_14_newSpiData),
    .ledByteOut(M_panel_14_ledByteOut),
    .ramPixelAddress(M_panel_14_ramPixelAddress),
    .idle(M_panel_14_idle),
    .out(M_panel_14_out)
  );
  wire [1-1:0] M_panel_15_newSpiData;
  wire [8-1:0] M_panel_15_ledByteOut;
  wire [10-1:0] M_panel_15_ramPixelAddress;
  wire [1-1:0] M_panel_15_idle;
  wire [1-1:0] M_panel_15_out;
  reg [1-1:0] M_panel_15_spiBusySignal;
  reg [24-1:0] M_panel_15_rgbIn;
  reg [1-1:0] M_panel_15_startWritingFlag;
  panel_15_19 panel_15 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_15_spiBusySignal),
    .rgbIn(M_panel_15_rgbIn),
    .startWritingFlag(M_panel_15_startWritingFlag),
    .newSpiData(M_panel_15_newSpiData),
    .ledByteOut(M_panel_15_ledByteOut),
    .ramPixelAddress(M_panel_15_ramPixelAddress),
    .idle(M_panel_15_idle),
    .out(M_panel_15_out)
  );
  wire [1-1:0] M_panel_16_newSpiData;
  wire [8-1:0] M_panel_16_ledByteOut;
  wire [10-1:0] M_panel_16_ramPixelAddress;
  wire [1-1:0] M_panel_16_idle;
  wire [1-1:0] M_panel_16_out;
  reg [1-1:0] M_panel_16_spiBusySignal;
  reg [24-1:0] M_panel_16_rgbIn;
  reg [1-1:0] M_panel_16_startWritingFlag;
  panel_16_20 panel_16 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_16_spiBusySignal),
    .rgbIn(M_panel_16_rgbIn),
    .startWritingFlag(M_panel_16_startWritingFlag),
    .newSpiData(M_panel_16_newSpiData),
    .ledByteOut(M_panel_16_ledByteOut),
    .ramPixelAddress(M_panel_16_ramPixelAddress),
    .idle(M_panel_16_idle),
    .out(M_panel_16_out)
  );
  wire [1-1:0] M_panel_17_newSpiData;
  wire [8-1:0] M_panel_17_ledByteOut;
  wire [10-1:0] M_panel_17_ramPixelAddress;
  wire [1-1:0] M_panel_17_idle;
  wire [1-1:0] M_panel_17_out;
  reg [1-1:0] M_panel_17_spiBusySignal;
  reg [24-1:0] M_panel_17_rgbIn;
  reg [1-1:0] M_panel_17_startWritingFlag;
  panel_17_21 panel_17 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_17_spiBusySignal),
    .rgbIn(M_panel_17_rgbIn),
    .startWritingFlag(M_panel_17_startWritingFlag),
    .newSpiData(M_panel_17_newSpiData),
    .ledByteOut(M_panel_17_ledByteOut),
    .ramPixelAddress(M_panel_17_ramPixelAddress),
    .idle(M_panel_17_idle),
    .out(M_panel_17_out)
  );
  wire [1-1:0] M_panel_18_newSpiData;
  wire [8-1:0] M_panel_18_ledByteOut;
  wire [10-1:0] M_panel_18_ramPixelAddress;
  wire [1-1:0] M_panel_18_idle;
  wire [1-1:0] M_panel_18_out;
  reg [1-1:0] M_panel_18_spiBusySignal;
  reg [24-1:0] M_panel_18_rgbIn;
  reg [1-1:0] M_panel_18_startWritingFlag;
  panel_18_22 panel_18 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_18_spiBusySignal),
    .rgbIn(M_panel_18_rgbIn),
    .startWritingFlag(M_panel_18_startWritingFlag),
    .newSpiData(M_panel_18_newSpiData),
    .ledByteOut(M_panel_18_ledByteOut),
    .ramPixelAddress(M_panel_18_ramPixelAddress),
    .idle(M_panel_18_idle),
    .out(M_panel_18_out)
  );
  wire [1-1:0] M_panel_19_newSpiData;
  wire [8-1:0] M_panel_19_ledByteOut;
  wire [10-1:0] M_panel_19_ramPixelAddress;
  wire [1-1:0] M_panel_19_idle;
  wire [1-1:0] M_panel_19_out;
  reg [1-1:0] M_panel_19_spiBusySignal;
  reg [24-1:0] M_panel_19_rgbIn;
  reg [1-1:0] M_panel_19_startWritingFlag;
  panel_19_23 panel_19 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_19_spiBusySignal),
    .rgbIn(M_panel_19_rgbIn),
    .startWritingFlag(M_panel_19_startWritingFlag),
    .newSpiData(M_panel_19_newSpiData),
    .ledByteOut(M_panel_19_ledByteOut),
    .ramPixelAddress(M_panel_19_ramPixelAddress),
    .idle(M_panel_19_idle),
    .out(M_panel_19_out)
  );
  wire [1-1:0] M_panel_20_newSpiData;
  wire [8-1:0] M_panel_20_ledByteOut;
  wire [10-1:0] M_panel_20_ramPixelAddress;
  wire [1-1:0] M_panel_20_idle;
  wire [1-1:0] M_panel_20_out;
  reg [1-1:0] M_panel_20_spiBusySignal;
  reg [24-1:0] M_panel_20_rgbIn;
  reg [1-1:0] M_panel_20_startWritingFlag;
  panel_20_24 panel_20 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_20_spiBusySignal),
    .rgbIn(M_panel_20_rgbIn),
    .startWritingFlag(M_panel_20_startWritingFlag),
    .newSpiData(M_panel_20_newSpiData),
    .ledByteOut(M_panel_20_ledByteOut),
    .ramPixelAddress(M_panel_20_ramPixelAddress),
    .idle(M_panel_20_idle),
    .out(M_panel_20_out)
  );
  wire [1-1:0] M_panel_21_newSpiData;
  wire [8-1:0] M_panel_21_ledByteOut;
  wire [10-1:0] M_panel_21_ramPixelAddress;
  wire [1-1:0] M_panel_21_idle;
  wire [1-1:0] M_panel_21_out;
  reg [1-1:0] M_panel_21_spiBusySignal;
  reg [24-1:0] M_panel_21_rgbIn;
  reg [1-1:0] M_panel_21_startWritingFlag;
  panel_21_25 panel_21 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_21_spiBusySignal),
    .rgbIn(M_panel_21_rgbIn),
    .startWritingFlag(M_panel_21_startWritingFlag),
    .newSpiData(M_panel_21_newSpiData),
    .ledByteOut(M_panel_21_ledByteOut),
    .ramPixelAddress(M_panel_21_ramPixelAddress),
    .idle(M_panel_21_idle),
    .out(M_panel_21_out)
  );
  wire [1-1:0] M_panel_22_newSpiData;
  wire [8-1:0] M_panel_22_ledByteOut;
  wire [10-1:0] M_panel_22_ramPixelAddress;
  wire [1-1:0] M_panel_22_idle;
  wire [1-1:0] M_panel_22_out;
  reg [1-1:0] M_panel_22_spiBusySignal;
  reg [24-1:0] M_panel_22_rgbIn;
  reg [1-1:0] M_panel_22_startWritingFlag;
  panel_22_26 panel_22 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_22_spiBusySignal),
    .rgbIn(M_panel_22_rgbIn),
    .startWritingFlag(M_panel_22_startWritingFlag),
    .newSpiData(M_panel_22_newSpiData),
    .ledByteOut(M_panel_22_ledByteOut),
    .ramPixelAddress(M_panel_22_ramPixelAddress),
    .idle(M_panel_22_idle),
    .out(M_panel_22_out)
  );
  wire [1-1:0] M_panel_23_newSpiData;
  wire [8-1:0] M_panel_23_ledByteOut;
  wire [10-1:0] M_panel_23_ramPixelAddress;
  wire [1-1:0] M_panel_23_idle;
  wire [1-1:0] M_panel_23_out;
  reg [1-1:0] M_panel_23_spiBusySignal;
  reg [24-1:0] M_panel_23_rgbIn;
  reg [1-1:0] M_panel_23_startWritingFlag;
  panel_23_27 panel_23 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_23_spiBusySignal),
    .rgbIn(M_panel_23_rgbIn),
    .startWritingFlag(M_panel_23_startWritingFlag),
    .newSpiData(M_panel_23_newSpiData),
    .ledByteOut(M_panel_23_ledByteOut),
    .ramPixelAddress(M_panel_23_ramPixelAddress),
    .idle(M_panel_23_idle),
    .out(M_panel_23_out)
  );
  wire [1-1:0] M_panel_24_newSpiData;
  wire [8-1:0] M_panel_24_ledByteOut;
  wire [10-1:0] M_panel_24_ramPixelAddress;
  wire [1-1:0] M_panel_24_idle;
  wire [1-1:0] M_panel_24_out;
  reg [1-1:0] M_panel_24_spiBusySignal;
  reg [24-1:0] M_panel_24_rgbIn;
  reg [1-1:0] M_panel_24_startWritingFlag;
  panel_24_28 panel_24 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_24_spiBusySignal),
    .rgbIn(M_panel_24_rgbIn),
    .startWritingFlag(M_panel_24_startWritingFlag),
    .newSpiData(M_panel_24_newSpiData),
    .ledByteOut(M_panel_24_ledByteOut),
    .ramPixelAddress(M_panel_24_ramPixelAddress),
    .idle(M_panel_24_idle),
    .out(M_panel_24_out)
  );
  wire [1-1:0] M_panel_25_newSpiData;
  wire [8-1:0] M_panel_25_ledByteOut;
  wire [10-1:0] M_panel_25_ramPixelAddress;
  wire [1-1:0] M_panel_25_idle;
  wire [1-1:0] M_panel_25_out;
  reg [1-1:0] M_panel_25_spiBusySignal;
  reg [24-1:0] M_panel_25_rgbIn;
  reg [1-1:0] M_panel_25_startWritingFlag;
  panel_25_29 panel_25 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_25_spiBusySignal),
    .rgbIn(M_panel_25_rgbIn),
    .startWritingFlag(M_panel_25_startWritingFlag),
    .newSpiData(M_panel_25_newSpiData),
    .ledByteOut(M_panel_25_ledByteOut),
    .ramPixelAddress(M_panel_25_ramPixelAddress),
    .idle(M_panel_25_idle),
    .out(M_panel_25_out)
  );
  wire [1-1:0] M_panel_26_newSpiData;
  wire [8-1:0] M_panel_26_ledByteOut;
  wire [10-1:0] M_panel_26_ramPixelAddress;
  wire [1-1:0] M_panel_26_idle;
  wire [1-1:0] M_panel_26_out;
  reg [1-1:0] M_panel_26_spiBusySignal;
  reg [24-1:0] M_panel_26_rgbIn;
  reg [1-1:0] M_panel_26_startWritingFlag;
  panel_26_30 panel_26 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_26_spiBusySignal),
    .rgbIn(M_panel_26_rgbIn),
    .startWritingFlag(M_panel_26_startWritingFlag),
    .newSpiData(M_panel_26_newSpiData),
    .ledByteOut(M_panel_26_ledByteOut),
    .ramPixelAddress(M_panel_26_ramPixelAddress),
    .idle(M_panel_26_idle),
    .out(M_panel_26_out)
  );
  wire [1-1:0] M_panel_27_newSpiData;
  wire [8-1:0] M_panel_27_ledByteOut;
  wire [10-1:0] M_panel_27_ramPixelAddress;
  wire [1-1:0] M_panel_27_idle;
  wire [1-1:0] M_panel_27_out;
  reg [1-1:0] M_panel_27_spiBusySignal;
  reg [24-1:0] M_panel_27_rgbIn;
  reg [1-1:0] M_panel_27_startWritingFlag;
  panel_27_31 panel_27 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_27_spiBusySignal),
    .rgbIn(M_panel_27_rgbIn),
    .startWritingFlag(M_panel_27_startWritingFlag),
    .newSpiData(M_panel_27_newSpiData),
    .ledByteOut(M_panel_27_ledByteOut),
    .ramPixelAddress(M_panel_27_ramPixelAddress),
    .idle(M_panel_27_idle),
    .out(M_panel_27_out)
  );
  wire [1-1:0] M_panel_28_newSpiData;
  wire [8-1:0] M_panel_28_ledByteOut;
  wire [10-1:0] M_panel_28_ramPixelAddress;
  wire [1-1:0] M_panel_28_idle;
  wire [1-1:0] M_panel_28_out;
  reg [1-1:0] M_panel_28_spiBusySignal;
  reg [24-1:0] M_panel_28_rgbIn;
  reg [1-1:0] M_panel_28_startWritingFlag;
  panel_28_32 panel_28 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_28_spiBusySignal),
    .rgbIn(M_panel_28_rgbIn),
    .startWritingFlag(M_panel_28_startWritingFlag),
    .newSpiData(M_panel_28_newSpiData),
    .ledByteOut(M_panel_28_ledByteOut),
    .ramPixelAddress(M_panel_28_ramPixelAddress),
    .idle(M_panel_28_idle),
    .out(M_panel_28_out)
  );
  wire [1-1:0] M_panel_29_newSpiData;
  wire [8-1:0] M_panel_29_ledByteOut;
  wire [10-1:0] M_panel_29_ramPixelAddress;
  wire [1-1:0] M_panel_29_idle;
  wire [1-1:0] M_panel_29_out;
  reg [1-1:0] M_panel_29_spiBusySignal;
  reg [24-1:0] M_panel_29_rgbIn;
  reg [1-1:0] M_panel_29_startWritingFlag;
  panel_29_33 panel_29 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_29_spiBusySignal),
    .rgbIn(M_panel_29_rgbIn),
    .startWritingFlag(M_panel_29_startWritingFlag),
    .newSpiData(M_panel_29_newSpiData),
    .ledByteOut(M_panel_29_ledByteOut),
    .ramPixelAddress(M_panel_29_ramPixelAddress),
    .idle(M_panel_29_idle),
    .out(M_panel_29_out)
  );
  wire [1-1:0] M_panel_30_newSpiData;
  wire [8-1:0] M_panel_30_ledByteOut;
  wire [10-1:0] M_panel_30_ramPixelAddress;
  wire [1-1:0] M_panel_30_idle;
  wire [1-1:0] M_panel_30_printSomething;
  wire [1-1:0] M_panel_30_out;
  reg [1-1:0] M_panel_30_spiBusySignal;
  reg [24-1:0] M_panel_30_rgbIn;
  reg [1-1:0] M_panel_30_startWritingFlag;
  panel_30_34 panel_30 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_30_spiBusySignal),
    .rgbIn(M_panel_30_rgbIn),
    .startWritingFlag(M_panel_30_startWritingFlag),
    .newSpiData(M_panel_30_newSpiData),
    .ledByteOut(M_panel_30_ledByteOut),
    .ramPixelAddress(M_panel_30_ramPixelAddress),
    .idle(M_panel_30_idle),
    .printSomething(M_panel_30_printSomething),
    .out(M_panel_30_out)
  );
  wire [1-1:0] M_panel_31_newSpiData;
  wire [8-1:0] M_panel_31_ledByteOut;
  wire [10-1:0] M_panel_31_ramPixelAddress;
  wire [1-1:0] M_panel_31_idle;
  wire [8-1:0] M_panel_31_transmitByte;
  wire [1-1:0] M_panel_31_newTxDataFlag;
  wire [1-1:0] M_panel_31_out;
  reg [1-1:0] M_panel_31_spiBusySignal;
  reg [24-1:0] M_panel_31_rgbIn;
  reg [1-1:0] M_panel_31_startWritingFlag;
  panel_31_35 panel_31 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_31_spiBusySignal),
    .rgbIn(M_panel_31_rgbIn),
    .startWritingFlag(M_panel_31_startWritingFlag),
    .newSpiData(M_panel_31_newSpiData),
    .ledByteOut(M_panel_31_ledByteOut),
    .ramPixelAddress(M_panel_31_ramPixelAddress),
    .idle(M_panel_31_idle),
    .transmitByte(M_panel_31_transmitByte),
    .newTxDataFlag(M_panel_31_newTxDataFlag),
    .out(M_panel_31_out)
  );
  wire [1-1:0] M_panel_32_newSpiData;
  wire [8-1:0] M_panel_32_ledByteOut;
  wire [10-1:0] M_panel_32_ramPixelAddress;
  wire [1-1:0] M_panel_32_idle;
  wire [8-1:0] M_panel_32_transmitByte;
  wire [1-1:0] M_panel_32_newTxDataFlag;
  wire [1-1:0] M_panel_32_out;
  reg [1-1:0] M_panel_32_spiBusySignal;
  reg [24-1:0] M_panel_32_rgbIn;
  reg [1-1:0] M_panel_32_startWritingFlag;
  panel_32_36 panel_32 (
    .clk(fclk),
    .rst(rst),
    .spiBusySignal(M_panel_32_spiBusySignal),
    .rgbIn(M_panel_32_rgbIn),
    .startWritingFlag(M_panel_32_startWritingFlag),
    .newSpiData(M_panel_32_newSpiData),
    .ledByteOut(M_panel_32_ledByteOut),
    .ramPixelAddress(M_panel_32_ramPixelAddress),
    .idle(M_panel_32_idle),
    .transmitByte(M_panel_32_transmitByte),
    .newTxDataFlag(M_panel_32_newTxDataFlag),
    .out(M_panel_32_out)
  );
  wire [1-1:0] M_spi_out0_mosi;
  wire [1-1:0] M_spi_out0_sck;
  wire [8-1:0] M_spi_out0_data_out;
  wire [1-1:0] M_spi_out0_new_data;
  wire [1-1:0] M_spi_out0_busy;
  reg [1-1:0] M_spi_out0_miso;
  reg [1-1:0] M_spi_out0_start;
  reg [8-1:0] M_spi_out0_data_in;
  spi_master0_37 spi_out0 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out0_miso),
    .start(M_spi_out0_start),
    .data_in(M_spi_out0_data_in),
    .mosi(M_spi_out0_mosi),
    .sck(M_spi_out0_sck),
    .data_out(M_spi_out0_data_out),
    .new_data(M_spi_out0_new_data),
    .busy(M_spi_out0_busy)
  );
  wire [1-1:0] M_spi_out1_mosi;
  wire [1-1:0] M_spi_out1_sck;
  wire [8-1:0] M_spi_out1_data_out;
  wire [1-1:0] M_spi_out1_new_data;
  wire [1-1:0] M_spi_out1_busy;
  reg [1-1:0] M_spi_out1_miso;
  reg [1-1:0] M_spi_out1_start;
  reg [8-1:0] M_spi_out1_data_in;
  spi_master1_38 spi_out1 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out1_miso),
    .start(M_spi_out1_start),
    .data_in(M_spi_out1_data_in),
    .mosi(M_spi_out1_mosi),
    .sck(M_spi_out1_sck),
    .data_out(M_spi_out1_data_out),
    .new_data(M_spi_out1_new_data),
    .busy(M_spi_out1_busy)
  );
  wire [1-1:0] M_spi_out2_mosi;
  wire [1-1:0] M_spi_out2_sck;
  wire [8-1:0] M_spi_out2_data_out;
  wire [1-1:0] M_spi_out2_new_data;
  wire [1-1:0] M_spi_out2_busy;
  reg [1-1:0] M_spi_out2_miso;
  reg [1-1:0] M_spi_out2_start;
  reg [8-1:0] M_spi_out2_data_in;
  spi_master2_39 spi_out2 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out2_miso),
    .start(M_spi_out2_start),
    .data_in(M_spi_out2_data_in),
    .mosi(M_spi_out2_mosi),
    .sck(M_spi_out2_sck),
    .data_out(M_spi_out2_data_out),
    .new_data(M_spi_out2_new_data),
    .busy(M_spi_out2_busy)
  );
  wire [1-1:0] M_spi_out3_mosi;
  wire [1-1:0] M_spi_out3_sck;
  wire [8-1:0] M_spi_out3_data_out;
  wire [1-1:0] M_spi_out3_new_data;
  wire [1-1:0] M_spi_out3_busy;
  reg [1-1:0] M_spi_out3_miso;
  reg [1-1:0] M_spi_out3_start;
  reg [8-1:0] M_spi_out3_data_in;
  spi_master3_40 spi_out3 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out3_miso),
    .start(M_spi_out3_start),
    .data_in(M_spi_out3_data_in),
    .mosi(M_spi_out3_mosi),
    .sck(M_spi_out3_sck),
    .data_out(M_spi_out3_data_out),
    .new_data(M_spi_out3_new_data),
    .busy(M_spi_out3_busy)
  );
  wire [1-1:0] M_spi_out4_mosi;
  wire [1-1:0] M_spi_out4_sck;
  wire [8-1:0] M_spi_out4_data_out;
  wire [1-1:0] M_spi_out4_new_data;
  wire [1-1:0] M_spi_out4_busy;
  reg [1-1:0] M_spi_out4_miso;
  reg [1-1:0] M_spi_out4_start;
  reg [8-1:0] M_spi_out4_data_in;
  spi_master4_41 spi_out4 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out4_miso),
    .start(M_spi_out4_start),
    .data_in(M_spi_out4_data_in),
    .mosi(M_spi_out4_mosi),
    .sck(M_spi_out4_sck),
    .data_out(M_spi_out4_data_out),
    .new_data(M_spi_out4_new_data),
    .busy(M_spi_out4_busy)
  );
  wire [1-1:0] M_spi_out5_mosi;
  wire [1-1:0] M_spi_out5_sck;
  wire [8-1:0] M_spi_out5_data_out;
  wire [1-1:0] M_spi_out5_new_data;
  wire [1-1:0] M_spi_out5_busy;
  reg [1-1:0] M_spi_out5_miso;
  reg [1-1:0] M_spi_out5_start;
  reg [8-1:0] M_spi_out5_data_in;
  spi_master5_42 spi_out5 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out5_miso),
    .start(M_spi_out5_start),
    .data_in(M_spi_out5_data_in),
    .mosi(M_spi_out5_mosi),
    .sck(M_spi_out5_sck),
    .data_out(M_spi_out5_data_out),
    .new_data(M_spi_out5_new_data),
    .busy(M_spi_out5_busy)
  );
  wire [1-1:0] M_spi_out6_mosi;
  wire [1-1:0] M_spi_out6_sck;
  wire [8-1:0] M_spi_out6_data_out;
  wire [1-1:0] M_spi_out6_new_data;
  wire [1-1:0] M_spi_out6_busy;
  reg [1-1:0] M_spi_out6_miso;
  reg [1-1:0] M_spi_out6_start;
  reg [8-1:0] M_spi_out6_data_in;
  spi_master6_43 spi_out6 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out6_miso),
    .start(M_spi_out6_start),
    .data_in(M_spi_out6_data_in),
    .mosi(M_spi_out6_mosi),
    .sck(M_spi_out6_sck),
    .data_out(M_spi_out6_data_out),
    .new_data(M_spi_out6_new_data),
    .busy(M_spi_out6_busy)
  );
  wire [1-1:0] M_spi_out7_mosi;
  wire [1-1:0] M_spi_out7_sck;
  wire [8-1:0] M_spi_out7_data_out;
  wire [1-1:0] M_spi_out7_new_data;
  wire [1-1:0] M_spi_out7_busy;
  reg [1-1:0] M_spi_out7_miso;
  reg [1-1:0] M_spi_out7_start;
  reg [8-1:0] M_spi_out7_data_in;
  spi_master7_44 spi_out7 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out7_miso),
    .start(M_spi_out7_start),
    .data_in(M_spi_out7_data_in),
    .mosi(M_spi_out7_mosi),
    .sck(M_spi_out7_sck),
    .data_out(M_spi_out7_data_out),
    .new_data(M_spi_out7_new_data),
    .busy(M_spi_out7_busy)
  );
  wire [1-1:0] M_spi_out8_mosi;
  wire [1-1:0] M_spi_out8_sck;
  wire [8-1:0] M_spi_out8_data_out;
  wire [1-1:0] M_spi_out8_new_data;
  wire [1-1:0] M_spi_out8_busy;
  reg [1-1:0] M_spi_out8_miso;
  reg [1-1:0] M_spi_out8_start;
  reg [8-1:0] M_spi_out8_data_in;
  spi_master8_45 spi_out8 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out8_miso),
    .start(M_spi_out8_start),
    .data_in(M_spi_out8_data_in),
    .mosi(M_spi_out8_mosi),
    .sck(M_spi_out8_sck),
    .data_out(M_spi_out8_data_out),
    .new_data(M_spi_out8_new_data),
    .busy(M_spi_out8_busy)
  );
  wire [1-1:0] M_spi_out9_mosi;
  wire [1-1:0] M_spi_out9_sck;
  wire [8-1:0] M_spi_out9_data_out;
  wire [1-1:0] M_spi_out9_new_data;
  wire [1-1:0] M_spi_out9_busy;
  reg [1-1:0] M_spi_out9_miso;
  reg [1-1:0] M_spi_out9_start;
  reg [8-1:0] M_spi_out9_data_in;
  spi_master9_46 spi_out9 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out9_miso),
    .start(M_spi_out9_start),
    .data_in(M_spi_out9_data_in),
    .mosi(M_spi_out9_mosi),
    .sck(M_spi_out9_sck),
    .data_out(M_spi_out9_data_out),
    .new_data(M_spi_out9_new_data),
    .busy(M_spi_out9_busy)
  );
  wire [1-1:0] M_spi_out10_mosi;
  wire [1-1:0] M_spi_out10_sck;
  wire [8-1:0] M_spi_out10_data_out;
  wire [1-1:0] M_spi_out10_new_data;
  wire [1-1:0] M_spi_out10_busy;
  reg [1-1:0] M_spi_out10_miso;
  reg [1-1:0] M_spi_out10_start;
  reg [8-1:0] M_spi_out10_data_in;
  spi_master10_47 spi_out10 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out10_miso),
    .start(M_spi_out10_start),
    .data_in(M_spi_out10_data_in),
    .mosi(M_spi_out10_mosi),
    .sck(M_spi_out10_sck),
    .data_out(M_spi_out10_data_out),
    .new_data(M_spi_out10_new_data),
    .busy(M_spi_out10_busy)
  );
  wire [1-1:0] M_spi_out11_mosi;
  wire [1-1:0] M_spi_out11_sck;
  wire [8-1:0] M_spi_out11_data_out;
  wire [1-1:0] M_spi_out11_new_data;
  wire [1-1:0] M_spi_out11_busy;
  reg [1-1:0] M_spi_out11_miso;
  reg [1-1:0] M_spi_out11_start;
  reg [8-1:0] M_spi_out11_data_in;
  spi_master11_48 spi_out11 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out11_miso),
    .start(M_spi_out11_start),
    .data_in(M_spi_out11_data_in),
    .mosi(M_spi_out11_mosi),
    .sck(M_spi_out11_sck),
    .data_out(M_spi_out11_data_out),
    .new_data(M_spi_out11_new_data),
    .busy(M_spi_out11_busy)
  );
  wire [1-1:0] M_spi_out12_mosi;
  wire [1-1:0] M_spi_out12_sck;
  wire [8-1:0] M_spi_out12_data_out;
  wire [1-1:0] M_spi_out12_new_data;
  wire [1-1:0] M_spi_out12_busy;
  reg [1-1:0] M_spi_out12_miso;
  reg [1-1:0] M_spi_out12_start;
  reg [8-1:0] M_spi_out12_data_in;
  spi_master12_49 spi_out12 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out12_miso),
    .start(M_spi_out12_start),
    .data_in(M_spi_out12_data_in),
    .mosi(M_spi_out12_mosi),
    .sck(M_spi_out12_sck),
    .data_out(M_spi_out12_data_out),
    .new_data(M_spi_out12_new_data),
    .busy(M_spi_out12_busy)
  );
  wire [1-1:0] M_spi_out13_mosi;
  wire [1-1:0] M_spi_out13_sck;
  wire [8-1:0] M_spi_out13_data_out;
  wire [1-1:0] M_spi_out13_new_data;
  wire [1-1:0] M_spi_out13_busy;
  reg [1-1:0] M_spi_out13_miso;
  reg [1-1:0] M_spi_out13_start;
  reg [8-1:0] M_spi_out13_data_in;
  spi_master13_50 spi_out13 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out13_miso),
    .start(M_spi_out13_start),
    .data_in(M_spi_out13_data_in),
    .mosi(M_spi_out13_mosi),
    .sck(M_spi_out13_sck),
    .data_out(M_spi_out13_data_out),
    .new_data(M_spi_out13_new_data),
    .busy(M_spi_out13_busy)
  );
  wire [1-1:0] M_spi_out14_mosi;
  wire [1-1:0] M_spi_out14_sck;
  wire [8-1:0] M_spi_out14_data_out;
  wire [1-1:0] M_spi_out14_new_data;
  wire [1-1:0] M_spi_out14_busy;
  reg [1-1:0] M_spi_out14_miso;
  reg [1-1:0] M_spi_out14_start;
  reg [8-1:0] M_spi_out14_data_in;
  spi_master14_51 spi_out14 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out14_miso),
    .start(M_spi_out14_start),
    .data_in(M_spi_out14_data_in),
    .mosi(M_spi_out14_mosi),
    .sck(M_spi_out14_sck),
    .data_out(M_spi_out14_data_out),
    .new_data(M_spi_out14_new_data),
    .busy(M_spi_out14_busy)
  );
  wire [1-1:0] M_spi_out15_mosi;
  wire [1-1:0] M_spi_out15_sck;
  wire [8-1:0] M_spi_out15_data_out;
  wire [1-1:0] M_spi_out15_new_data;
  wire [1-1:0] M_spi_out15_busy;
  reg [1-1:0] M_spi_out15_miso;
  reg [1-1:0] M_spi_out15_start;
  reg [8-1:0] M_spi_out15_data_in;
  spi_master15_52 spi_out15 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out15_miso),
    .start(M_spi_out15_start),
    .data_in(M_spi_out15_data_in),
    .mosi(M_spi_out15_mosi),
    .sck(M_spi_out15_sck),
    .data_out(M_spi_out15_data_out),
    .new_data(M_spi_out15_new_data),
    .busy(M_spi_out15_busy)
  );
  wire [1-1:0] M_spi_out16_mosi;
  wire [1-1:0] M_spi_out16_sck;
  wire [8-1:0] M_spi_out16_data_out;
  wire [1-1:0] M_spi_out16_new_data;
  wire [1-1:0] M_spi_out16_busy;
  reg [1-1:0] M_spi_out16_miso;
  reg [1-1:0] M_spi_out16_start;
  reg [8-1:0] M_spi_out16_data_in;
  spi_master16_53 spi_out16 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out16_miso),
    .start(M_spi_out16_start),
    .data_in(M_spi_out16_data_in),
    .mosi(M_spi_out16_mosi),
    .sck(M_spi_out16_sck),
    .data_out(M_spi_out16_data_out),
    .new_data(M_spi_out16_new_data),
    .busy(M_spi_out16_busy)
  );
  wire [1-1:0] M_spi_out17_mosi;
  wire [1-1:0] M_spi_out17_sck;
  wire [8-1:0] M_spi_out17_data_out;
  wire [1-1:0] M_spi_out17_new_data;
  wire [1-1:0] M_spi_out17_busy;
  reg [1-1:0] M_spi_out17_miso;
  reg [1-1:0] M_spi_out17_start;
  reg [8-1:0] M_spi_out17_data_in;
  spi_master17_54 spi_out17 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out17_miso),
    .start(M_spi_out17_start),
    .data_in(M_spi_out17_data_in),
    .mosi(M_spi_out17_mosi),
    .sck(M_spi_out17_sck),
    .data_out(M_spi_out17_data_out),
    .new_data(M_spi_out17_new_data),
    .busy(M_spi_out17_busy)
  );
  wire [1-1:0] M_spi_out18_mosi;
  wire [1-1:0] M_spi_out18_sck;
  wire [8-1:0] M_spi_out18_data_out;
  wire [1-1:0] M_spi_out18_new_data;
  wire [1-1:0] M_spi_out18_busy;
  reg [1-1:0] M_spi_out18_miso;
  reg [1-1:0] M_spi_out18_start;
  reg [8-1:0] M_spi_out18_data_in;
  spi_master18_55 spi_out18 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out18_miso),
    .start(M_spi_out18_start),
    .data_in(M_spi_out18_data_in),
    .mosi(M_spi_out18_mosi),
    .sck(M_spi_out18_sck),
    .data_out(M_spi_out18_data_out),
    .new_data(M_spi_out18_new_data),
    .busy(M_spi_out18_busy)
  );
  wire [1-1:0] M_spi_out19_mosi;
  wire [1-1:0] M_spi_out19_sck;
  wire [8-1:0] M_spi_out19_data_out;
  wire [1-1:0] M_spi_out19_new_data;
  wire [1-1:0] M_spi_out19_busy;
  reg [1-1:0] M_spi_out19_miso;
  reg [1-1:0] M_spi_out19_start;
  reg [8-1:0] M_spi_out19_data_in;
  spi_master19_56 spi_out19 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out19_miso),
    .start(M_spi_out19_start),
    .data_in(M_spi_out19_data_in),
    .mosi(M_spi_out19_mosi),
    .sck(M_spi_out19_sck),
    .data_out(M_spi_out19_data_out),
    .new_data(M_spi_out19_new_data),
    .busy(M_spi_out19_busy)
  );
  wire [1-1:0] M_spi_out20_mosi;
  wire [1-1:0] M_spi_out20_sck;
  wire [8-1:0] M_spi_out20_data_out;
  wire [1-1:0] M_spi_out20_new_data;
  wire [1-1:0] M_spi_out20_busy;
  reg [1-1:0] M_spi_out20_miso;
  reg [1-1:0] M_spi_out20_start;
  reg [8-1:0] M_spi_out20_data_in;
  spi_master20_57 spi_out20 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out20_miso),
    .start(M_spi_out20_start),
    .data_in(M_spi_out20_data_in),
    .mosi(M_spi_out20_mosi),
    .sck(M_spi_out20_sck),
    .data_out(M_spi_out20_data_out),
    .new_data(M_spi_out20_new_data),
    .busy(M_spi_out20_busy)
  );
  wire [1-1:0] M_spi_out21_mosi;
  wire [1-1:0] M_spi_out21_sck;
  wire [8-1:0] M_spi_out21_data_out;
  wire [1-1:0] M_spi_out21_new_data;
  wire [1-1:0] M_spi_out21_busy;
  reg [1-1:0] M_spi_out21_miso;
  reg [1-1:0] M_spi_out21_start;
  reg [8-1:0] M_spi_out21_data_in;
  spi_master21_58 spi_out21 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out21_miso),
    .start(M_spi_out21_start),
    .data_in(M_spi_out21_data_in),
    .mosi(M_spi_out21_mosi),
    .sck(M_spi_out21_sck),
    .data_out(M_spi_out21_data_out),
    .new_data(M_spi_out21_new_data),
    .busy(M_spi_out21_busy)
  );
  wire [1-1:0] M_spi_out22_mosi;
  wire [1-1:0] M_spi_out22_sck;
  wire [8-1:0] M_spi_out22_data_out;
  wire [1-1:0] M_spi_out22_new_data;
  wire [1-1:0] M_spi_out22_busy;
  reg [1-1:0] M_spi_out22_miso;
  reg [1-1:0] M_spi_out22_start;
  reg [8-1:0] M_spi_out22_data_in;
  spi_master22_59 spi_out22 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out22_miso),
    .start(M_spi_out22_start),
    .data_in(M_spi_out22_data_in),
    .mosi(M_spi_out22_mosi),
    .sck(M_spi_out22_sck),
    .data_out(M_spi_out22_data_out),
    .new_data(M_spi_out22_new_data),
    .busy(M_spi_out22_busy)
  );
  wire [1-1:0] M_spi_out23_mosi;
  wire [1-1:0] M_spi_out23_sck;
  wire [8-1:0] M_spi_out23_data_out;
  wire [1-1:0] M_spi_out23_new_data;
  wire [1-1:0] M_spi_out23_busy;
  reg [1-1:0] M_spi_out23_miso;
  reg [1-1:0] M_spi_out23_start;
  reg [8-1:0] M_spi_out23_data_in;
  spi_master23_60 spi_out23 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out23_miso),
    .start(M_spi_out23_start),
    .data_in(M_spi_out23_data_in),
    .mosi(M_spi_out23_mosi),
    .sck(M_spi_out23_sck),
    .data_out(M_spi_out23_data_out),
    .new_data(M_spi_out23_new_data),
    .busy(M_spi_out23_busy)
  );
  wire [1-1:0] M_spi_out24_mosi;
  wire [1-1:0] M_spi_out24_sck;
  wire [8-1:0] M_spi_out24_data_out;
  wire [1-1:0] M_spi_out24_new_data;
  wire [1-1:0] M_spi_out24_busy;
  reg [1-1:0] M_spi_out24_miso;
  reg [1-1:0] M_spi_out24_start;
  reg [8-1:0] M_spi_out24_data_in;
  spi_master24_61 spi_out24 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out24_miso),
    .start(M_spi_out24_start),
    .data_in(M_spi_out24_data_in),
    .mosi(M_spi_out24_mosi),
    .sck(M_spi_out24_sck),
    .data_out(M_spi_out24_data_out),
    .new_data(M_spi_out24_new_data),
    .busy(M_spi_out24_busy)
  );
  wire [1-1:0] M_spi_out25_mosi;
  wire [1-1:0] M_spi_out25_sck;
  wire [8-1:0] M_spi_out25_data_out;
  wire [1-1:0] M_spi_out25_new_data;
  wire [1-1:0] M_spi_out25_busy;
  reg [1-1:0] M_spi_out25_miso;
  reg [1-1:0] M_spi_out25_start;
  reg [8-1:0] M_spi_out25_data_in;
  spi_master25_62 spi_out25 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out25_miso),
    .start(M_spi_out25_start),
    .data_in(M_spi_out25_data_in),
    .mosi(M_spi_out25_mosi),
    .sck(M_spi_out25_sck),
    .data_out(M_spi_out25_data_out),
    .new_data(M_spi_out25_new_data),
    .busy(M_spi_out25_busy)
  );
  wire [1-1:0] M_spi_out26_mosi;
  wire [1-1:0] M_spi_out26_sck;
  wire [8-1:0] M_spi_out26_data_out;
  wire [1-1:0] M_spi_out26_new_data;
  wire [1-1:0] M_spi_out26_busy;
  reg [1-1:0] M_spi_out26_miso;
  reg [1-1:0] M_spi_out26_start;
  reg [8-1:0] M_spi_out26_data_in;
  spi_master26_63 spi_out26 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out26_miso),
    .start(M_spi_out26_start),
    .data_in(M_spi_out26_data_in),
    .mosi(M_spi_out26_mosi),
    .sck(M_spi_out26_sck),
    .data_out(M_spi_out26_data_out),
    .new_data(M_spi_out26_new_data),
    .busy(M_spi_out26_busy)
  );
  wire [1-1:0] M_spi_out27_mosi;
  wire [1-1:0] M_spi_out27_sck;
  wire [8-1:0] M_spi_out27_data_out;
  wire [1-1:0] M_spi_out27_new_data;
  wire [1-1:0] M_spi_out27_busy;
  reg [1-1:0] M_spi_out27_miso;
  reg [1-1:0] M_spi_out27_start;
  reg [8-1:0] M_spi_out27_data_in;
  spi_master27_64 spi_out27 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out27_miso),
    .start(M_spi_out27_start),
    .data_in(M_spi_out27_data_in),
    .mosi(M_spi_out27_mosi),
    .sck(M_spi_out27_sck),
    .data_out(M_spi_out27_data_out),
    .new_data(M_spi_out27_new_data),
    .busy(M_spi_out27_busy)
  );
  wire [1-1:0] M_spi_out28_mosi;
  wire [1-1:0] M_spi_out28_sck;
  wire [8-1:0] M_spi_out28_data_out;
  wire [1-1:0] M_spi_out28_new_data;
  wire [1-1:0] M_spi_out28_busy;
  reg [1-1:0] M_spi_out28_miso;
  reg [1-1:0] M_spi_out28_start;
  reg [8-1:0] M_spi_out28_data_in;
  spi_master28_65 spi_out28 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out28_miso),
    .start(M_spi_out28_start),
    .data_in(M_spi_out28_data_in),
    .mosi(M_spi_out28_mosi),
    .sck(M_spi_out28_sck),
    .data_out(M_spi_out28_data_out),
    .new_data(M_spi_out28_new_data),
    .busy(M_spi_out28_busy)
  );
  wire [1-1:0] M_spi_out29_mosi;
  wire [1-1:0] M_spi_out29_sck;
  wire [8-1:0] M_spi_out29_data_out;
  wire [1-1:0] M_spi_out29_new_data;
  wire [1-1:0] M_spi_out29_busy;
  reg [1-1:0] M_spi_out29_miso;
  reg [1-1:0] M_spi_out29_start;
  reg [8-1:0] M_spi_out29_data_in;
  spi_master29_66 spi_out29 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out29_miso),
    .start(M_spi_out29_start),
    .data_in(M_spi_out29_data_in),
    .mosi(M_spi_out29_mosi),
    .sck(M_spi_out29_sck),
    .data_out(M_spi_out29_data_out),
    .new_data(M_spi_out29_new_data),
    .busy(M_spi_out29_busy)
  );
  wire [1-1:0] M_spi_out30_mosi;
  wire [1-1:0] M_spi_out30_sck;
  wire [8-1:0] M_spi_out30_data_out;
  wire [1-1:0] M_spi_out30_new_data;
  wire [1-1:0] M_spi_out30_busy;
  reg [1-1:0] M_spi_out30_miso;
  reg [1-1:0] M_spi_out30_start;
  reg [8-1:0] M_spi_out30_data_in;
  spi_master30_67 spi_out30 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out30_miso),
    .start(M_spi_out30_start),
    .data_in(M_spi_out30_data_in),
    .mosi(M_spi_out30_mosi),
    .sck(M_spi_out30_sck),
    .data_out(M_spi_out30_data_out),
    .new_data(M_spi_out30_new_data),
    .busy(M_spi_out30_busy)
  );
  wire [1-1:0] M_spi_out31_mosi;
  wire [1-1:0] M_spi_out31_sck;
  wire [8-1:0] M_spi_out31_data_out;
  wire [1-1:0] M_spi_out31_new_data;
  wire [1-1:0] M_spi_out31_busy;
  reg [1-1:0] M_spi_out31_miso;
  reg [1-1:0] M_spi_out31_start;
  reg [8-1:0] M_spi_out31_data_in;
  spi_master31_68 spi_out31 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out31_miso),
    .start(M_spi_out31_start),
    .data_in(M_spi_out31_data_in),
    .mosi(M_spi_out31_mosi),
    .sck(M_spi_out31_sck),
    .data_out(M_spi_out31_data_out),
    .new_data(M_spi_out31_new_data),
    .busy(M_spi_out31_busy)
  );
  wire [1-1:0] M_spi_out32_mosi;
  wire [1-1:0] M_spi_out32_sck;
  wire [8-1:0] M_spi_out32_data_out;
  wire [1-1:0] M_spi_out32_new_data;
  wire [1-1:0] M_spi_out32_busy;
  reg [1-1:0] M_spi_out32_miso;
  reg [1-1:0] M_spi_out32_start;
  reg [8-1:0] M_spi_out32_data_in;
  spi_master32_69 spi_out32 (
    .clk(fclk),
    .rst(rst),
    .miso(M_spi_out32_miso),
    .start(M_spi_out32_start),
    .data_in(M_spi_out32_data_in),
    .mosi(M_spi_out32_mosi),
    .sck(M_spi_out32_sck),
    .data_out(M_spi_out32_data_out),
    .new_data(M_spi_out32_new_data),
    .busy(M_spi_out32_busy)
  );
  wire [4-1:0] M_fifo_buffer_currentFrame;
  wire [1-1:0] M_fifo_buffer_printSomething;
  wire [24-1:0] M_fifo_buffer_postFifoPixelCount;
  wire [24-1:0] M_fifo_buffer_rgbOut0;
  wire [24-1:0] M_fifo_buffer_rgbOut1;
  wire [24-1:0] M_fifo_buffer_rgbOut2;
  wire [24-1:0] M_fifo_buffer_rgbOut3;
  wire [24-1:0] M_fifo_buffer_rgbOut4;
  wire [24-1:0] M_fifo_buffer_rgbOut5;
  wire [24-1:0] M_fifo_buffer_rgbOut6;
  wire [24-1:0] M_fifo_buffer_rgbOut7;
  wire [24-1:0] M_fifo_buffer_rgbOut8;
  wire [24-1:0] M_fifo_buffer_rgbOut9;
  wire [24-1:0] M_fifo_buffer_rgbOut10;
  wire [24-1:0] M_fifo_buffer_rgbOut11;
  wire [24-1:0] M_fifo_buffer_rgbOut12;
  wire [24-1:0] M_fifo_buffer_rgbOut13;
  wire [24-1:0] M_fifo_buffer_rgbOut14;
  wire [24-1:0] M_fifo_buffer_rgbOut15;
  wire [24-1:0] M_fifo_buffer_rgbOut16;
  wire [24-1:0] M_fifo_buffer_rgbOut17;
  wire [24-1:0] M_fifo_buffer_rgbOut18;
  wire [24-1:0] M_fifo_buffer_rgbOut19;
  wire [24-1:0] M_fifo_buffer_rgbOut20;
  wire [24-1:0] M_fifo_buffer_rgbOut21;
  wire [24-1:0] M_fifo_buffer_rgbOut22;
  wire [24-1:0] M_fifo_buffer_rgbOut23;
  wire [24-1:0] M_fifo_buffer_rgbOut24;
  wire [24-1:0] M_fifo_buffer_rgbOut25;
  wire [24-1:0] M_fifo_buffer_rgbOut26;
  wire [24-1:0] M_fifo_buffer_rgbOut27;
  wire [24-1:0] M_fifo_buffer_rgbOut28;
  wire [24-1:0] M_fifo_buffer_rgbOut29;
  wire [24-1:0] M_fifo_buffer_rgbOut30;
  wire [24-1:0] M_fifo_buffer_rgbOut31;
  wire [24-1:0] M_fifo_buffer_rgbOut32;
  wire [1-1:0] M_fifo_buffer_startWritingFlag;
  wire [1-1:0] M_fifo_buffer_startWritingFlag1;
  wire [1-1:0] M_fifo_buffer_startWritingFlag2;
  wire [1-1:0] M_fifo_buffer_startWritingFlag3;
  wire [1-1:0] M_fifo_buffer_startWritingFlag4;
  wire [1-1:0] M_fifo_buffer_startWritingFlag5;
  wire [1-1:0] M_fifo_buffer_startWritingFlag6;
  wire [1-1:0] M_fifo_buffer_startWritingFlag7;
  wire [1-1:0] M_fifo_buffer_startWritingFlag8;
  wire [1-1:0] M_fifo_buffer_startWritingFlag9;
  wire [1-1:0] M_fifo_buffer_startWritingFlag10;
  wire [5-1:0] M_fifo_buffer_rowPixelAddress;
  wire [24-1:0] M_fifo_buffer_notConnected;
  reg [1-1:0] M_fifo_buffer_hdmi_clk;
  reg [1-1:0] M_fifo_buffer_hdmi_vsyncFlag;
  reg [2-1:0] M_fifo_buffer_globalReadWriteStageFlag;
  reg [8-1:0] M_fifo_buffer_redIn;
  reg [8-1:0] M_fifo_buffer_greenIn;
  reg [8-1:0] M_fifo_buffer_blueIn;
  reg [1-1:0] M_fifo_buffer_writeFifo;
  reg [1-1:0] M_fifo_buffer_notWriting;
  reg [10-1:0] M_fifo_buffer_writePixelAddress0;
  reg [10-1:0] M_fifo_buffer_writePixelAddress1;
  reg [10-1:0] M_fifo_buffer_writePixelAddress2;
  reg [10-1:0] M_fifo_buffer_writePixelAddress3;
  reg [10-1:0] M_fifo_buffer_writePixelAddress4;
  reg [10-1:0] M_fifo_buffer_writePixelAddress5;
  reg [10-1:0] M_fifo_buffer_writePixelAddress6;
  reg [10-1:0] M_fifo_buffer_writePixelAddress7;
  reg [10-1:0] M_fifo_buffer_writePixelAddress8;
  reg [10-1:0] M_fifo_buffer_writePixelAddress9;
  reg [10-1:0] M_fifo_buffer_writePixelAddress10;
  reg [10-1:0] M_fifo_buffer_writePixelAddress11;
  reg [10-1:0] M_fifo_buffer_writePixelAddress12;
  reg [10-1:0] M_fifo_buffer_writePixelAddress13;
  reg [10-1:0] M_fifo_buffer_writePixelAddress14;
  reg [10-1:0] M_fifo_buffer_writePixelAddress15;
  reg [10-1:0] M_fifo_buffer_writePixelAddress16;
  reg [10-1:0] M_fifo_buffer_writePixelAddress17;
  reg [10-1:0] M_fifo_buffer_writePixelAddress18;
  reg [10-1:0] M_fifo_buffer_writePixelAddress19;
  reg [10-1:0] M_fifo_buffer_writePixelAddress20;
  reg [10-1:0] M_fifo_buffer_writePixelAddress21;
  reg [10-1:0] M_fifo_buffer_writePixelAddress22;
  reg [10-1:0] M_fifo_buffer_writePixelAddress23;
  reg [10-1:0] M_fifo_buffer_writePixelAddress24;
  reg [10-1:0] M_fifo_buffer_writePixelAddress25;
  reg [10-1:0] M_fifo_buffer_writePixelAddress26;
  reg [10-1:0] M_fifo_buffer_writePixelAddress27;
  reg [10-1:0] M_fifo_buffer_writePixelAddress28;
  reg [10-1:0] M_fifo_buffer_writePixelAddress29;
  reg [10-1:0] M_fifo_buffer_writePixelAddress30;
  reg [10-1:0] M_fifo_buffer_writePixelAddress31;
  reg [10-1:0] M_fifo_buffer_writePixelAddress32;
  reg [10-1:0] M_fifo_buffer_startPixel0;
  reg [10-1:0] M_fifo_buffer_startPixel1;
  reg [10-1:0] M_fifo_buffer_startPixel2;
  reg [10-1:0] M_fifo_buffer_rowStartPixel0;
  reg [10-1:0] M_fifo_buffer_rowStartPixel1;
  reg [10-1:0] M_fifo_buffer_rowStartPixel2;
  reg [10-1:0] M_fifo_buffer_rowStartPixel3;
  reg [10-1:0] M_fifo_buffer_rowStartPixel4;
  reg [10-1:0] M_fifo_buffer_rowStartPixel5;
  reg [10-1:0] M_fifo_buffer_rowStartPixel7;
  fifo_buffer_70 fifo_buffer (
    .clk(fclk),
    .rst(rst),
    .hdmi_clk(M_fifo_buffer_hdmi_clk),
    .hdmi_vsyncFlag(M_fifo_buffer_hdmi_vsyncFlag),
    .globalReadWriteStageFlag(M_fifo_buffer_globalReadWriteStageFlag),
    .redIn(M_fifo_buffer_redIn),
    .greenIn(M_fifo_buffer_greenIn),
    .blueIn(M_fifo_buffer_blueIn),
    .writeFifo(M_fifo_buffer_writeFifo),
    .notWriting(M_fifo_buffer_notWriting),
    .writePixelAddress0(M_fifo_buffer_writePixelAddress0),
    .writePixelAddress1(M_fifo_buffer_writePixelAddress1),
    .writePixelAddress2(M_fifo_buffer_writePixelAddress2),
    .writePixelAddress3(M_fifo_buffer_writePixelAddress3),
    .writePixelAddress4(M_fifo_buffer_writePixelAddress4),
    .writePixelAddress5(M_fifo_buffer_writePixelAddress5),
    .writePixelAddress6(M_fifo_buffer_writePixelAddress6),
    .writePixelAddress7(M_fifo_buffer_writePixelAddress7),
    .writePixelAddress8(M_fifo_buffer_writePixelAddress8),
    .writePixelAddress9(M_fifo_buffer_writePixelAddress9),
    .writePixelAddress10(M_fifo_buffer_writePixelAddress10),
    .writePixelAddress11(M_fifo_buffer_writePixelAddress11),
    .writePixelAddress12(M_fifo_buffer_writePixelAddress12),
    .writePixelAddress13(M_fifo_buffer_writePixelAddress13),
    .writePixelAddress14(M_fifo_buffer_writePixelAddress14),
    .writePixelAddress15(M_fifo_buffer_writePixelAddress15),
    .writePixelAddress16(M_fifo_buffer_writePixelAddress16),
    .writePixelAddress17(M_fifo_buffer_writePixelAddress17),
    .writePixelAddress18(M_fifo_buffer_writePixelAddress18),
    .writePixelAddress19(M_fifo_buffer_writePixelAddress19),
    .writePixelAddress20(M_fifo_buffer_writePixelAddress20),
    .writePixelAddress21(M_fifo_buffer_writePixelAddress21),
    .writePixelAddress22(M_fifo_buffer_writePixelAddress22),
    .writePixelAddress23(M_fifo_buffer_writePixelAddress23),
    .writePixelAddress24(M_fifo_buffer_writePixelAddress24),
    .writePixelAddress25(M_fifo_buffer_writePixelAddress25),
    .writePixelAddress26(M_fifo_buffer_writePixelAddress26),
    .writePixelAddress27(M_fifo_buffer_writePixelAddress27),
    .writePixelAddress28(M_fifo_buffer_writePixelAddress28),
    .writePixelAddress29(M_fifo_buffer_writePixelAddress29),
    .writePixelAddress30(M_fifo_buffer_writePixelAddress30),
    .writePixelAddress31(M_fifo_buffer_writePixelAddress31),
    .writePixelAddress32(M_fifo_buffer_writePixelAddress32),
    .startPixel0(M_fifo_buffer_startPixel0),
    .startPixel1(M_fifo_buffer_startPixel1),
    .startPixel2(M_fifo_buffer_startPixel2),
    .rowStartPixel0(M_fifo_buffer_rowStartPixel0),
    .rowStartPixel1(M_fifo_buffer_rowStartPixel1),
    .rowStartPixel2(M_fifo_buffer_rowStartPixel2),
    .rowStartPixel3(M_fifo_buffer_rowStartPixel3),
    .rowStartPixel4(M_fifo_buffer_rowStartPixel4),
    .rowStartPixel5(M_fifo_buffer_rowStartPixel5),
    .rowStartPixel7(M_fifo_buffer_rowStartPixel7),
    .currentFrame(M_fifo_buffer_currentFrame),
    .printSomething(M_fifo_buffer_printSomething),
    .postFifoPixelCount(M_fifo_buffer_postFifoPixelCount),
    .rgbOut0(M_fifo_buffer_rgbOut0),
    .rgbOut1(M_fifo_buffer_rgbOut1),
    .rgbOut2(M_fifo_buffer_rgbOut2),
    .rgbOut3(M_fifo_buffer_rgbOut3),
    .rgbOut4(M_fifo_buffer_rgbOut4),
    .rgbOut5(M_fifo_buffer_rgbOut5),
    .rgbOut6(M_fifo_buffer_rgbOut6),
    .rgbOut7(M_fifo_buffer_rgbOut7),
    .rgbOut8(M_fifo_buffer_rgbOut8),
    .rgbOut9(M_fifo_buffer_rgbOut9),
    .rgbOut10(M_fifo_buffer_rgbOut10),
    .rgbOut11(M_fifo_buffer_rgbOut11),
    .rgbOut12(M_fifo_buffer_rgbOut12),
    .rgbOut13(M_fifo_buffer_rgbOut13),
    .rgbOut14(M_fifo_buffer_rgbOut14),
    .rgbOut15(M_fifo_buffer_rgbOut15),
    .rgbOut16(M_fifo_buffer_rgbOut16),
    .rgbOut17(M_fifo_buffer_rgbOut17),
    .rgbOut18(M_fifo_buffer_rgbOut18),
    .rgbOut19(M_fifo_buffer_rgbOut19),
    .rgbOut20(M_fifo_buffer_rgbOut20),
    .rgbOut21(M_fifo_buffer_rgbOut21),
    .rgbOut22(M_fifo_buffer_rgbOut22),
    .rgbOut23(M_fifo_buffer_rgbOut23),
    .rgbOut24(M_fifo_buffer_rgbOut24),
    .rgbOut25(M_fifo_buffer_rgbOut25),
    .rgbOut26(M_fifo_buffer_rgbOut26),
    .rgbOut27(M_fifo_buffer_rgbOut27),
    .rgbOut28(M_fifo_buffer_rgbOut28),
    .rgbOut29(M_fifo_buffer_rgbOut29),
    .rgbOut30(M_fifo_buffer_rgbOut30),
    .rgbOut31(M_fifo_buffer_rgbOut31),
    .rgbOut32(M_fifo_buffer_rgbOut32),
    .startWritingFlag(M_fifo_buffer_startWritingFlag),
    .startWritingFlag1(M_fifo_buffer_startWritingFlag1),
    .startWritingFlag2(M_fifo_buffer_startWritingFlag2),
    .startWritingFlag3(M_fifo_buffer_startWritingFlag3),
    .startWritingFlag4(M_fifo_buffer_startWritingFlag4),
    .startWritingFlag5(M_fifo_buffer_startWritingFlag5),
    .startWritingFlag6(M_fifo_buffer_startWritingFlag6),
    .startWritingFlag7(M_fifo_buffer_startWritingFlag7),
    .startWritingFlag8(M_fifo_buffer_startWritingFlag8),
    .startWritingFlag9(M_fifo_buffer_startWritingFlag9),
    .startWritingFlag10(M_fifo_buffer_startWritingFlag10),
    .rowPixelAddress(M_fifo_buffer_rowPixelAddress),
    .notConnected(M_fifo_buffer_notConnected)
  );
  wire [1-1:0] M_avr_spi_miso;
  wire [4-1:0] M_avr_spi_channel;
  wire [1-1:0] M_avr_tx;
  wire [1-1:0] M_avr_new_sample;
  wire [10-1:0] M_avr_sample;
  wire [4-1:0] M_avr_sample_channel;
  wire [1-1:0] M_avr_tx_busy;
  wire [8-1:0] M_avr_rx_data;
  wire [1-1:0] M_avr_new_rx_data;
  reg [1-1:0] M_avr_cclk;
  reg [1-1:0] M_avr_spi_mosi;
  reg [1-1:0] M_avr_spi_sck;
  reg [1-1:0] M_avr_spi_ss;
  reg [1-1:0] M_avr_rx;
  reg [4-1:0] M_avr_channel;
  reg [8-1:0] M_avr_tx_data;
  reg [1-1:0] M_avr_new_tx_data;
  reg [1-1:0] M_avr_tx_block;
  avr_interface_71 avr (
    .clk(fclk),
    .rst(rst),
    .cclk(M_avr_cclk),
    .spi_mosi(M_avr_spi_mosi),
    .spi_sck(M_avr_spi_sck),
    .spi_ss(M_avr_spi_ss),
    .rx(M_avr_rx),
    .channel(M_avr_channel),
    .tx_data(M_avr_tx_data),
    .new_tx_data(M_avr_new_tx_data),
    .tx_block(M_avr_tx_block),
    .spi_miso(M_avr_spi_miso),
    .spi_channel(M_avr_spi_channel),
    .tx(M_avr_tx),
    .new_sample(M_avr_new_sample),
    .sample(M_avr_sample),
    .sample_channel(M_avr_sample_channel),
    .tx_busy(M_avr_tx_busy),
    .rx_data(M_avr_rx_data),
    .new_rx_data(M_avr_new_rx_data)
  );
  reg [2:0] M_readWriteStage_d, M_readWriteStage_q = 1'h0;
  edid_rom_72 edid (
    .clk(fclk),
    .rst(rst),
    .sda(hdmi2_sda),
    .scl(hdmi2_scl)
  );
  
  always @* begin
    M_readWriteStage_d = M_readWriteStage_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_avr_cclk = cclk;
    M_avr_spi_ss = spi_ss;
    M_avr_spi_mosi = spi_mosi;
    M_avr_spi_sck = spi_sck;
    M_avr_rx = avr_tx;
    M_avr_channel = 4'hf;
    M_avr_tx_block = avr_rx_busy;
    spi_miso = M_avr_spi_miso;
    spi_channel = M_avr_spi_channel;
    avr_rx = M_avr_tx;
    M_avr_new_tx_data = 1'h0;
    M_avr_tx_data = 1'h0;
    M_fifo_buffer_hdmi_clk = M_hdmi_to_fifo_hdmiClk;
    M_fifo_buffer_writeFifo = M_hdmi_to_fifo_writeFifo;
    M_fifo_buffer_redIn = M_hdmi_to_fifo_redOut;
    M_fifo_buffer_greenIn = M_hdmi_to_fifo_greenOut;
    M_fifo_buffer_blueIn = M_hdmi_to_fifo_blueOut;
    M_fifo_buffer_hdmi_vsyncFlag = M_hdmi_to_fifo_hdmi_vsyncFlag;
    M_fifo_buffer_notWriting = M_panel_0_idle;
    M_hdmi_to_fifo_tmds = hdmi2_tmds;
    M_hdmi_to_fifo_tmdsb = hdmi2_tmdsb;
    M_panelRows_currentFrame = M_fifo_buffer_currentFrame;
    M_fifo_buffer_startPixel0 = M_panelRows_startPixel0;
    M_fifo_buffer_startPixel1 = M_panelRows_startPixel1;
    M_fifo_buffer_startPixel2 = M_panelRows_startPixel2;
    M_fifo_buffer_writePixelAddress0 = M_panel_0_ramPixelAddress;
    M_fifo_buffer_writePixelAddress1 = M_panel_1_ramPixelAddress;
    M_fifo_buffer_writePixelAddress2 = M_panel_2_ramPixelAddress;
    M_fifo_buffer_writePixelAddress3 = M_panel_3_ramPixelAddress;
    M_fifo_buffer_writePixelAddress4 = M_panel_4_ramPixelAddress;
    M_fifo_buffer_writePixelAddress5 = M_panel_5_ramPixelAddress;
    M_fifo_buffer_writePixelAddress6 = M_panel_6_ramPixelAddress;
    M_fifo_buffer_writePixelAddress7 = M_panel_7_ramPixelAddress;
    M_fifo_buffer_writePixelAddress8 = M_panel_8_ramPixelAddress;
    M_fifo_buffer_writePixelAddress9 = M_panel_9_ramPixelAddress;
    M_fifo_buffer_writePixelAddress10 = M_panel_10_ramPixelAddress;
    M_fifo_buffer_writePixelAddress11 = M_panel_11_ramPixelAddress;
    M_fifo_buffer_writePixelAddress12 = M_panel_12_ramPixelAddress;
    M_fifo_buffer_writePixelAddress13 = M_panel_13_ramPixelAddress;
    M_fifo_buffer_writePixelAddress14 = M_panel_14_ramPixelAddress;
    M_fifo_buffer_writePixelAddress15 = M_panel_15_ramPixelAddress;
    M_fifo_buffer_writePixelAddress16 = M_panel_16_ramPixelAddress;
    M_fifo_buffer_writePixelAddress17 = M_panel_17_ramPixelAddress;
    M_fifo_buffer_writePixelAddress18 = M_panel_18_ramPixelAddress;
    M_fifo_buffer_writePixelAddress19 = M_panel_19_ramPixelAddress;
    M_fifo_buffer_writePixelAddress20 = M_panel_20_ramPixelAddress;
    M_fifo_buffer_writePixelAddress21 = M_panel_21_ramPixelAddress;
    M_fifo_buffer_writePixelAddress22 = M_panel_22_ramPixelAddress;
    M_fifo_buffer_writePixelAddress23 = M_panel_23_ramPixelAddress;
    M_fifo_buffer_writePixelAddress24 = M_panel_24_ramPixelAddress;
    M_fifo_buffer_writePixelAddress25 = M_panel_25_ramPixelAddress;
    M_fifo_buffer_writePixelAddress26 = M_panel_26_ramPixelAddress;
    M_fifo_buffer_writePixelAddress27 = M_panel_27_ramPixelAddress;
    M_fifo_buffer_writePixelAddress28 = M_panel_28_ramPixelAddress;
    M_fifo_buffer_writePixelAddress29 = M_panel_29_ramPixelAddress;
    M_fifo_buffer_writePixelAddress30 = M_panel_30_ramPixelAddress;
    M_fifo_buffer_writePixelAddress31 = M_panel_31_ramPixelAddress;
    M_fifo_buffer_writePixelAddress32 = M_panel_32_ramPixelAddress;
    M_panel_0_rgbIn = M_fifo_buffer_rgbOut0;
    M_panel_1_rgbIn = M_fifo_buffer_rgbOut1;
    M_panel_2_rgbIn = M_fifo_buffer_rgbOut2;
    M_panel_3_rgbIn = M_fifo_buffer_rgbOut3;
    M_panel_4_rgbIn = M_fifo_buffer_rgbOut4;
    M_panel_5_rgbIn = M_fifo_buffer_rgbOut5;
    M_panel_6_rgbIn = M_fifo_buffer_rgbOut6;
    M_panel_7_rgbIn = M_fifo_buffer_rgbOut7;
    M_panel_8_rgbIn = M_fifo_buffer_rgbOut8;
    M_panel_9_rgbIn = M_fifo_buffer_rgbOut9;
    M_panel_10_rgbIn = M_fifo_buffer_rgbOut10;
    M_panel_11_rgbIn = M_fifo_buffer_rgbOut11;
    M_panel_12_rgbIn = M_fifo_buffer_rgbOut12;
    M_panel_13_rgbIn = M_fifo_buffer_rgbOut13;
    M_panel_14_rgbIn = M_fifo_buffer_rgbOut14;
    M_panel_15_rgbIn = M_fifo_buffer_rgbOut15;
    M_panel_16_rgbIn = M_fifo_buffer_rgbOut16;
    M_panel_17_rgbIn = M_fifo_buffer_rgbOut17;
    M_panel_18_rgbIn = M_fifo_buffer_rgbOut18;
    M_panel_19_rgbIn = M_fifo_buffer_rgbOut19;
    M_panel_20_rgbIn = M_fifo_buffer_rgbOut20;
    M_panel_21_rgbIn = M_fifo_buffer_rgbOut21;
    M_panel_22_rgbIn = M_fifo_buffer_rgbOut22;
    M_panel_23_rgbIn = M_fifo_buffer_rgbOut23;
    M_panel_24_rgbIn = M_fifo_buffer_rgbOut24;
    M_panel_25_rgbIn = M_fifo_buffer_rgbOut25;
    M_panel_26_rgbIn = M_fifo_buffer_rgbOut26;
    M_panel_27_rgbIn = M_fifo_buffer_rgbOut27;
    M_panel_28_rgbIn = M_fifo_buffer_rgbOut28;
    M_panel_29_rgbIn = M_fifo_buffer_rgbOut29;
    M_panel_30_rgbIn = M_fifo_buffer_rgbOut30;
    M_panel_31_rgbIn = M_fifo_buffer_rgbOut31;
    M_panel_32_rgbIn = M_fifo_buffer_rgbOut32;
    M_panelRows_address0 = M_fifo_buffer_rowPixelAddress;
    M_fifo_buffer_rowStartPixel0 = M_panelRows_rowPixelPanel0;
    M_fifo_buffer_rowStartPixel1 = M_panelRows_rowPixelPanel1;
    M_fifo_buffer_rowStartPixel2 = M_panelRows_rowPixelPanel2;
    M_fifo_buffer_rowStartPixel3 = M_panelRows_rowPixelPanel3;
    M_fifo_buffer_rowStartPixel4 = M_panelRows_rowPixelPanel4;
    M_fifo_buffer_rowStartPixel5 = M_panelRows_rowPixelPanel5;
    M_fifo_buffer_rowStartPixel7 = M_panelRows_rowPixelPanel7;
    M_panel_0_startWritingFlag = M_fifo_buffer_startWritingFlag;
    M_panel_1_startWritingFlag = M_fifo_buffer_startWritingFlag;
    M_panel_2_startWritingFlag = M_fifo_buffer_startWritingFlag;
    M_panel_3_startWritingFlag = M_fifo_buffer_startWritingFlag1;
    M_panel_4_startWritingFlag = M_fifo_buffer_startWritingFlag1;
    M_panel_5_startWritingFlag = M_fifo_buffer_startWritingFlag1;
    M_panel_6_startWritingFlag = M_fifo_buffer_startWritingFlag2;
    M_panel_7_startWritingFlag = M_fifo_buffer_startWritingFlag2;
    M_panel_8_startWritingFlag = M_fifo_buffer_startWritingFlag2;
    M_panel_9_startWritingFlag = M_fifo_buffer_startWritingFlag3;
    M_panel_10_startWritingFlag = M_fifo_buffer_startWritingFlag3;
    M_panel_11_startWritingFlag = M_fifo_buffer_startWritingFlag3;
    M_panel_12_startWritingFlag = M_fifo_buffer_startWritingFlag4;
    M_panel_13_startWritingFlag = M_fifo_buffer_startWritingFlag4;
    M_panel_14_startWritingFlag = M_fifo_buffer_startWritingFlag4;
    M_panel_15_startWritingFlag = M_fifo_buffer_startWritingFlag5;
    M_panel_16_startWritingFlag = M_fifo_buffer_startWritingFlag5;
    M_panel_17_startWritingFlag = M_fifo_buffer_startWritingFlag5;
    M_panel_18_startWritingFlag = M_fifo_buffer_startWritingFlag6;
    M_panel_19_startWritingFlag = M_fifo_buffer_startWritingFlag6;
    M_panel_20_startWritingFlag = M_fifo_buffer_startWritingFlag6;
    M_panel_21_startWritingFlag = M_fifo_buffer_startWritingFlag7;
    M_panel_22_startWritingFlag = M_fifo_buffer_startWritingFlag7;
    M_panel_23_startWritingFlag = M_fifo_buffer_startWritingFlag7;
    M_panel_24_startWritingFlag = M_fifo_buffer_startWritingFlag8;
    M_panel_25_startWritingFlag = M_fifo_buffer_startWritingFlag8;
    M_panel_26_startWritingFlag = M_fifo_buffer_startWritingFlag8;
    M_panel_27_startWritingFlag = M_fifo_buffer_startWritingFlag9;
    M_panel_28_startWritingFlag = M_fifo_buffer_startWritingFlag9;
    M_panel_29_startWritingFlag = M_fifo_buffer_startWritingFlag9;
    M_panel_30_startWritingFlag = M_fifo_buffer_startWritingFlag10;
    M_panel_31_startWritingFlag = M_fifo_buffer_startWritingFlag10;
    M_panel_32_startWritingFlag = M_fifo_buffer_startWritingFlag10;
    M_spi_out0_data_in = M_panel_0_ledByteOut;
    M_spi_out0_start = M_panel_0_newSpiData;
    M_panel_0_spiBusySignal = M_spi_out0_busy;
    M_spi_out1_data_in = M_panel_1_ledByteOut;
    M_spi_out1_start = M_panel_1_newSpiData;
    M_panel_1_spiBusySignal = M_spi_out1_busy;
    M_spi_out2_data_in = M_panel_2_ledByteOut;
    M_spi_out2_start = M_panel_2_newSpiData;
    M_panel_2_spiBusySignal = M_spi_out2_busy;
    M_spi_out3_data_in = M_panel_3_ledByteOut;
    M_spi_out3_start = M_panel_3_newSpiData;
    M_panel_3_spiBusySignal = M_spi_out3_busy;
    M_spi_out4_data_in = M_panel_4_ledByteOut;
    M_spi_out4_start = M_panel_4_newSpiData;
    M_panel_4_spiBusySignal = M_spi_out4_busy;
    M_spi_out5_data_in = M_panel_5_ledByteOut;
    M_spi_out5_start = M_panel_5_newSpiData;
    M_panel_5_spiBusySignal = M_spi_out5_busy;
    M_spi_out6_data_in = M_panel_6_ledByteOut;
    M_spi_out6_start = M_panel_6_newSpiData;
    M_panel_6_spiBusySignal = M_spi_out6_busy;
    M_spi_out7_data_in = M_panel_7_ledByteOut;
    M_spi_out7_start = M_panel_7_newSpiData;
    M_panel_7_spiBusySignal = M_spi_out7_busy;
    M_spi_out8_data_in = M_panel_8_ledByteOut;
    M_spi_out8_start = M_panel_8_newSpiData;
    M_panel_8_spiBusySignal = M_spi_out8_busy;
    M_spi_out9_data_in = M_panel_9_ledByteOut;
    M_spi_out9_start = M_panel_9_newSpiData;
    M_panel_9_spiBusySignal = M_spi_out9_busy;
    M_spi_out10_data_in = M_panel_10_ledByteOut;
    M_spi_out10_start = M_panel_10_newSpiData;
    M_panel_10_spiBusySignal = M_spi_out10_busy;
    M_spi_out11_data_in = M_panel_11_ledByteOut;
    M_spi_out11_start = M_panel_11_newSpiData;
    M_panel_11_spiBusySignal = M_spi_out11_busy;
    M_spi_out12_data_in = M_panel_12_ledByteOut;
    M_spi_out12_start = M_panel_12_newSpiData;
    M_panel_12_spiBusySignal = M_spi_out12_busy;
    M_spi_out13_data_in = M_panel_13_ledByteOut;
    M_spi_out13_start = M_panel_13_newSpiData;
    M_panel_13_spiBusySignal = M_spi_out13_busy;
    M_spi_out14_data_in = M_panel_14_ledByteOut;
    M_spi_out14_start = M_panel_14_newSpiData;
    M_panel_14_spiBusySignal = M_spi_out14_busy;
    M_spi_out15_data_in = M_panel_15_ledByteOut;
    M_spi_out15_start = M_panel_15_newSpiData;
    M_panel_15_spiBusySignal = M_spi_out15_busy;
    M_spi_out16_data_in = M_panel_16_ledByteOut;
    M_spi_out16_start = M_panel_16_newSpiData;
    M_panel_16_spiBusySignal = M_spi_out16_busy;
    M_spi_out17_data_in = M_panel_17_ledByteOut;
    M_spi_out17_start = M_panel_17_newSpiData;
    M_panel_17_spiBusySignal = M_spi_out17_busy;
    M_spi_out18_data_in = M_panel_18_ledByteOut;
    M_spi_out18_start = M_panel_18_newSpiData;
    M_panel_18_spiBusySignal = M_spi_out18_busy;
    M_spi_out19_data_in = M_panel_19_ledByteOut;
    M_spi_out19_start = M_panel_19_newSpiData;
    M_panel_19_spiBusySignal = M_spi_out19_busy;
    M_spi_out20_data_in = M_panel_20_ledByteOut;
    M_spi_out20_start = M_panel_20_newSpiData;
    M_panel_20_spiBusySignal = M_spi_out20_busy;
    M_spi_out21_data_in = M_panel_21_ledByteOut;
    M_spi_out21_start = M_panel_21_newSpiData;
    M_panel_21_spiBusySignal = M_spi_out21_busy;
    M_spi_out22_data_in = M_panel_22_ledByteOut;
    M_spi_out22_start = M_panel_22_newSpiData;
    M_panel_22_spiBusySignal = M_spi_out22_busy;
    M_spi_out23_data_in = M_panel_23_ledByteOut;
    M_spi_out23_start = M_panel_23_newSpiData;
    M_panel_23_spiBusySignal = M_spi_out23_busy;
    M_spi_out24_data_in = M_panel_24_ledByteOut;
    M_spi_out24_start = M_panel_24_newSpiData;
    M_panel_24_spiBusySignal = M_spi_out24_busy;
    M_spi_out25_data_in = M_panel_25_ledByteOut;
    M_spi_out25_start = M_panel_25_newSpiData;
    M_panel_25_spiBusySignal = M_spi_out25_busy;
    M_spi_out26_data_in = M_panel_26_ledByteOut;
    M_spi_out26_start = M_panel_26_newSpiData;
    M_panel_26_spiBusySignal = M_spi_out26_busy;
    M_spi_out27_data_in = M_panel_27_ledByteOut;
    M_spi_out27_start = M_panel_27_newSpiData;
    M_panel_27_spiBusySignal = M_spi_out27_busy;
    M_spi_out28_data_in = M_panel_28_ledByteOut;
    M_spi_out28_start = M_panel_28_newSpiData;
    M_panel_28_spiBusySignal = M_spi_out28_busy;
    M_spi_out29_data_in = M_panel_29_ledByteOut;
    M_spi_out29_start = M_panel_29_newSpiData;
    M_panel_29_spiBusySignal = M_spi_out29_busy;
    M_spi_out30_data_in = M_panel_30_ledByteOut;
    M_spi_out30_start = M_panel_30_newSpiData;
    M_panel_30_spiBusySignal = M_spi_out30_busy;
    M_spi_out31_data_in = M_panel_31_ledByteOut;
    M_spi_out31_start = M_panel_31_newSpiData;
    M_panel_31_spiBusySignal = M_spi_out31_busy;
    M_spi_out32_data_in = M_panel_32_ledByteOut;
    M_spi_out32_start = M_panel_32_newSpiData;
    M_panel_32_spiBusySignal = M_spi_out32_busy;
    M_spi_out0_miso = 1'h0;
    M_spi_out1_miso = 1'h0;
    M_spi_out2_miso = 1'h0;
    M_spi_out3_miso = 1'h0;
    M_spi_out4_miso = 1'h0;
    M_spi_out5_miso = 1'h0;
    M_spi_out6_miso = 1'h0;
    M_spi_out7_miso = 1'h0;
    M_spi_out8_miso = 1'h0;
    M_spi_out9_miso = 1'h0;
    M_spi_out10_miso = 1'h0;
    M_spi_out11_miso = 1'h0;
    M_spi_out12_miso = 1'h0;
    M_spi_out13_miso = 1'h0;
    M_spi_out14_miso = 1'h0;
    M_spi_out15_miso = 1'h0;
    M_spi_out16_miso = 1'h0;
    M_spi_out17_miso = 1'h0;
    M_spi_out18_miso = 1'h0;
    M_spi_out19_miso = 1'h0;
    M_spi_out20_miso = 1'h0;
    M_spi_out21_miso = 1'h0;
    M_spi_out22_miso = 1'h0;
    M_spi_out23_miso = 1'h0;
    M_spi_out24_miso = 1'h0;
    M_spi_out25_miso = 1'h0;
    M_spi_out26_miso = 1'h0;
    M_spi_out27_miso = 1'h0;
    M_spi_out28_miso = 1'h0;
    M_spi_out29_miso = 1'h0;
    M_spi_out30_miso = 1'h0;
    M_spi_out31_miso = 1'h0;
    M_spi_out32_miso = 1'h0;
    apa102_data0 = M_spi_out0_mosi;
    apa102_data1 = M_spi_out1_mosi;
    apa102_data2 = M_spi_out2_mosi;
    apa102_data3 = M_spi_out3_mosi;
    apa102_data4 = M_spi_out4_mosi;
    apa102_data5 = M_spi_out5_mosi;
    apa102_data6 = M_spi_out6_mosi;
    apa102_data7 = M_spi_out7_mosi;
    apa102_data8 = M_spi_out8_mosi;
    apa102_data9 = M_spi_out9_mosi;
    apa102_data10 = M_spi_out10_mosi;
    apa102_data11 = M_spi_out11_mosi;
    apa102_data12 = M_spi_out12_mosi;
    apa102_data13 = M_spi_out13_mosi;
    apa102_data14 = M_spi_out14_mosi;
    apa102_data15 = M_spi_out15_mosi;
    apa102_data16 = M_spi_out16_mosi;
    apa102_data17 = M_spi_out17_mosi;
    apa102_data18 = M_spi_out18_mosi;
    apa102_data19 = M_spi_out19_mosi;
    apa102_data20 = M_spi_out20_mosi;
    apa102_data21 = M_spi_out21_mosi;
    apa102_data22 = M_spi_out22_mosi;
    apa102_data23 = M_spi_out23_mosi;
    apa102_data24 = M_spi_out24_mosi;
    apa102_data25 = M_spi_out25_mosi;
    apa102_data26 = M_spi_out26_mosi;
    apa102_data27 = M_spi_out27_mosi;
    apa102_data28 = M_spi_out28_mosi;
    apa102_data29 = M_spi_out29_mosi;
    apa102_data31 = M_spi_out31_mosi;
    apa102_data32 = M_spi_out32_mosi;
    apa102_data30 = M_spi_out30_mosi;
    M_fifo_buffer_globalReadWriteStageFlag = M_hdmi_to_fifo_globalReadWriteStageFlag;
    M_readWriteStage_d = M_hdmi_to_fifo_globalReadWriteStageFlag;
    apa102_sck = 1'bx;
    if (M_readWriteStage_q == 1'h0) begin
      apa102_sck = M_spi_out0_sck;
      apa102_sck = M_spi_out1_sck;
      apa102_sck = M_spi_out2_sck;
      apa102_sck = M_spi_out9_sck;
      apa102_sck = M_spi_out10_sck;
      apa102_sck = M_spi_out11_sck;
      apa102_sck = M_spi_out15_sck;
      apa102_sck = M_spi_out16_sck;
      apa102_sck = M_spi_out17_sck;
    end
    if (M_readWriteStage_q == 1'h1) begin
      apa102_sck = M_spi_out3_sck;
      apa102_sck = M_spi_out4_sck;
      apa102_sck = M_spi_out5_sck;
      apa102_sck = M_spi_out12_sck;
      apa102_sck = M_spi_out13_sck;
      apa102_sck = M_spi_out14_sck;
      apa102_sck = M_spi_out21_sck;
      apa102_sck = M_spi_out22_sck;
      apa102_sck = M_spi_out23_sck;
      apa102_sck = M_spi_out27_sck;
      apa102_sck = M_spi_out28_sck;
      apa102_sck = M_spi_out29_sck;
    end
    if (M_readWriteStage_q == 2'h2) begin
      apa102_sck = M_spi_out6_sck;
      apa102_sck = M_spi_out7_sck;
      apa102_sck = M_spi_out8_sck;
      apa102_sck = M_spi_out18_sck;
      apa102_sck = M_spi_out19_sck;
      apa102_sck = M_spi_out20_sck;
      apa102_sck = M_spi_out24_sck;
      apa102_sck = M_spi_out25_sck;
      apa102_sck = M_spi_out26_sck;
      apa102_sck = M_spi_out30_sck;
      apa102_sck = M_spi_out31_sck;
      apa102_sck = M_spi_out32_sck;
    end
    if (M_readWriteStage_q == 2'h3) begin
      apa102_sck = M_spi_out30_sck;
      apa102_sck = M_spi_out31_sck;
      apa102_sck = M_spi_out32_sck;
    end
  end
  
  always @(posedge fclk) begin
    if (rst == 1'b1) begin
      M_readWriteStage_q <= 1'h0;
    end else begin
      M_readWriteStage_q <= M_readWriteStage_d;
    end
  end
  
endmodule
