/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module panelRows_1 (
    input [3:0] currentFrame,
    output reg [9:0] startPixel0,
    output reg [9:0] startPixel1,
    output reg [9:0] startPixel2,
    input [4:0] address0,
    output reg [9:0] rowPixelPanel0,
    output reg [9:0] rowPixelPanel1,
    output reg [9:0] rowPixelPanel2,
    output reg [9:0] rowPixelPanel3,
    output reg [9:0] rowPixelPanel4,
    output reg [9:0] rowPixelPanel5,
    output reg [9:0] rowPixelPanel7
  );
  
  
  
  localparam ARRAY_SIZE = 5'h14;
  
  reg [199:0] bottom_left_start;
  
  reg [199:0] bottom_right_start;
  
  reg [199:0] top_left_start;
  
  reg [199:0] top_left_start2;
  
  reg [199:0] top_right_start;
  
  localparam FRAMES = 4'hb;
  
  reg [109:0] pixels0;
  
  reg [109:0] pixels1;
  
  reg [109:0] pixels2;
  
  always @* begin
    bottom_left_start = 200'h0004311087220cb3310f4415355197661db7721f88263992a7;
    top_left_start = 200'ha9e6498e2087ddc76d9865d5454d1043ccc32c8821c4410c00;
    top_left_start2 = 200'ha9e6498e2087ddc76d9865d5454d1043ccc32c8821c4410c00;
    top_right_start = 200'ha1a8590a417f9fd6e9b95d9754c9313b8ed2a8a91986508821;
    bottom_right_start = 200'h08422194662a4aa3b4ee4c5325d5766e5ba7f5fe90642a1686;
    rowPixelPanel0 = bottom_left_start[(address0)*10+9-:10];
    rowPixelPanel1 = top_right_start[(address0)*10+9-:10];
    rowPixelPanel2 = bottom_left_start[(address0)*10+9-:10];
    rowPixelPanel3 = top_left_start[(address0)*10+9-:10];
    rowPixelPanel4 = top_right_start[(address0)*10+9-:10];
    rowPixelPanel5 = top_left_start2[(address0)*10+9-:10];
    rowPixelPanel7 = bottom_right_start[(address0)*10+9-:10];
    pixels0 = 110'h2a7a9ea7a9c00a9ea7a9ea7002a7;
    pixels1 = 110'h02108421a1821084210868608421;
    pixels2 = 110'h2a7a9ea7a9c00a9ea7a9ea7002a7;
    startPixel0 = pixels0[(currentFrame)*10+9-:10];
    startPixel1 = pixels1[(currentFrame)*10+9-:10];
    startPixel2 = pixels2[(currentFrame)*10+9-:10];
  end
endmodule
