<?xml version="1.0" encoding="UTF-8"?>
<project name="hdmi_In_test" board="Mojo V3" language="Lucid">
  <files>
    <src>spi_master29.luc</src>
    <src>panel_12.luc</src>
    <src>spi_master21.luc</src>
    <src>spi_master12.luc</src>
    <src>panel_23.luc</src>
    <src>panel_4.luc</src>
    <src>panel_14.luc</src>
    <src>panel_6.luc</src>
    <src>panel_10.luc</src>
    <src top="true">mojo_top.luc</src>
    <src>spi_master5.luc</src>
    <src>panel_31.luc</src>
    <src>spi_master19.luc</src>
    <src>panel_20.luc</src>
    <src>spi_master14.luc</src>
    <src>spi_master7.luc</src>
    <src>panel_18.luc</src>
    <src>spi_master31.luc</src>
    <src>spi_master3.luc</src>
    <src>panel_24.luc</src>
    <src>fifo_buffer.luc</src>
    <src>panel_30.luc</src>
    <src>spi_master25.luc</src>
    <src>panel_2.luc</src>
    <src>panel_5.luc</src>
    <src>panel_15.luc</src>
    <src>spi_master16.luc</src>
    <src>panel_1.luc</src>
    <src>spi_master4.luc</src>
    <src>spi_master17.luc</src>
    <src>spi_master0.luc</src>
    <src>panel_32.luc</src>
    <src>spi_master26.luc</src>
    <src>panel_17.luc</src>
    <src>spi_master9.luc</src>
    <src>spi_master18.luc</src>
    <src>panel_0.luc</src>
    <src>spi_master22.luc</src>
    <src>panel_13.luc</src>
    <src>panelRows.luc</src>
    <src>panel_29.luc</src>
    <src>panel_16.luc</src>
    <src>panel_25.luc</src>
    <src>panel_19.luc</src>
    <src>spi_master24.luc</src>
    <src>spi_master15.luc</src>
    <src>panel_3.luc</src>
    <src>spi_master32.luc</src>
    <src>spi_master27.luc</src>
    <src>hdmi_to_fifo.luc</src>
    <src>panel_27.luc</src>
    <src>panel_9.luc</src>
    <src>spi_master23.luc</src>
    <src>panel_7.luc</src>
    <src>panel_11.luc</src>
    <src>spi_master1.luc</src>
    <src>panel_21.luc</src>
    <src>panel_22.luc</src>
    <src>panel_8.luc</src>
    <src>spi_master28.luc</src>
    <src>spi_master6.luc</src>
    <src>spi_master20.luc</src>
    <src>spi_master10.luc</src>
    <src>spi_master30.luc</src>
    <src>panel_28.luc</src>
    <src>spi_master11.luc</src>
    <src>panel_26.luc</src>
    <src>spi_master2.luc</src>
    <src>spi_master8.luc</src>
    <src>spi_master13.luc</src>
    <ucf>led_strip.ucf</ucf>
    <ucf>hdmi_clock.ucf</ucf>
    <component>dvi_globals.luc</component>
    <component>spi_master.luc</component>
    <component>tmds_decoder.luc</component>
    <component>i2c_slave.luc</component>
    <component>dvi_decoder.luc</component>
    <component>uart_tx.luc</component>
    <component>channel_align.luc</component>
    <component>bit_align.luc</component>
    <component>spi_slave.luc</component>
    <component>async_fifo.luc</component>
    <component>uart_rx.luc</component>
    <component>simple_ram.v</component>
    <component>cclk_detector.luc</component>
    <component>reset_conditioner.luc</component>
    <component>edid_rom.luc</component>
    <component>simple_dual_ram.v</component>
    <component>avr_interface.luc</component>
    <component>serdes_1_to_5.luc</component>
    <core name="clk_wiz_v3_6">
      <src>clk_wiz_v3_6.v</src>
    </core>
  </files>
</project>
